(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(handempty)
		(on a m)
		(on b e)
		(on c f)
		(on d j)
		(on e c)
		(on g o)
		(on i n)
		(on j g)
		(on k i)
		(on l b)
		(on m l)
		(on n h)
		(on o k)
		(ontable f)
		(ontable h)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
