(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear e)
		(clear m)
		(clear o)
		(handempty)
		(on a h)
		(on b j)
		(on c g)
		(on e l)
		(on j n)
		(on l c)
		(on m i)
		(on n k)
		(on o f)
		(ontable d)
		(ontable f)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
