(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear j)
		(clear l)
		(clear m)
		(handempty)
		(on a o)
		(on b a)
		(on c n)
		(on d c)
		(on e i)
		(on f k)
		(on g e)
		(on i f)
		(on k b)
		(on m d)
		(on n g)
		(on o h)
		(ontable h)
		(ontable j)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
