(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear e)
		(clear h)
		(clear o)
		(handempty)
		(on a f)
		(on c g)
		(on f j)
		(on h m)
		(on i d)
		(on j n)
		(on l c)
		(on m k)
		(on n i)
		(on o l)
		(ontable b)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
