(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear j)
		(clear m)
		(handempty)
		(on b a)
		(on c o)
		(on d l)
		(on e n)
		(on f i)
		(on g d)
		(on h k)
		(on j h)
		(on k e)
		(on l f)
		(on m b)
		(on n g)
		(ontable a)
		(ontable i)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
