(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear g)
		(clear h)
		(clear j)
		(clear n)
		(clear o)
		(handempty)
		(on a f)
		(on b k)
		(on c b)
		(on e m)
		(on g e)
		(on h d)
		(on j a)
		(on l i)
		(on m l)
		(on n c)
		(ontable d)
		(ontable f)
		(ontable i)
		(ontable k)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
