(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear e)
		(clear n)
		(handempty)
		(on b a)
		(on c h)
		(on e o)
		(on f k)
		(on g d)
		(on h m)
		(on i f)
		(on j l)
		(on l c)
		(on m i)
		(on n g)
		(on o j)
		(ontable a)
		(ontable d)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
