(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear o)
		(handempty)
		(on a g)
		(on b e)
		(on c l)
		(on d a)
		(on e h)
		(on f k)
		(on g n)
		(on h i)
		(on i f)
		(on j b)
		(on m c)
		(on n j)
		(on o m)
		(ontable k)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
