(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear c)
		(clear g)
		(clear h)
		(clear i)
		(handempty)
		(on a d)
		(on b l)
		(on c k)
		(on d j)
		(on f a)
		(on i e)
		(on j m)
		(on l o)
		(on m n)
		(on o f)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable k)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
