(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear h)
		(clear i)
		(clear n)
		(clear o)
		(handempty)
		(on a d)
		(on b g)
		(on d l)
		(on f b)
		(on h j)
		(on i k)
		(on j e)
		(on k f)
		(on n m)
		(on o c)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable l)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
