(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear f)
		(clear g)
		(clear m)
		(handempty)
		(on b o)
		(on c e)
		(on d h)
		(on f c)
		(on g n)
		(on i d)
		(on j l)
		(on l a)
		(on m j)
		(on n k)
		(on o i)
		(ontable a)
		(ontable e)
		(ontable h)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
