(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear n)
		(handempty)
		(on a i)
		(on b e)
		(on c g)
		(on d l)
		(on e j)
		(on f k)
		(on h f)
		(on i b)
		(on j d)
		(on k m)
		(on l c)
		(on m o)
		(on n h)
		(on o a)
		(ontable g)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
