(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear c)
		(clear j)
		(clear k)
		(handempty)
		(on b f)
		(on c o)
		(on d h)
		(on e n)
		(on i l)
		(on j m)
		(on k e)
		(on l g)
		(on m i)
		(on n d)
		(on o a)
		(ontable a)
		(ontable f)
		(ontable g)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
