(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear e)
		(clear h)
		(clear j)
		(clear l)
		(handempty)
		(on b i)
		(on e m)
		(on f k)
		(on h n)
		(on i o)
		(on j g)
		(on k d)
		(on m b)
		(on n f)
		(on o a)
		(ontable a)
		(ontable c)
		(ontable d)
		(ontable g)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
