(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear g)
		(clear h)
		(clear j)
		(clear l)
		(handempty)
		(on a c)
		(on b m)
		(on c f)
		(on d b)
		(on f o)
		(on g i)
		(on h d)
		(on j e)
		(on l k)
		(on m n)
		(ontable e)
		(ontable i)
		(ontable k)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
