(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear g)
		(clear n)
		(handempty)
		(on a h)
		(on c e)
		(on d m)
		(on e k)
		(on f i)
		(on g c)
		(on h j)
		(on i l)
		(on j b)
		(on k o)
		(on m a)
		(on n d)
		(on o f)
		(ontable b)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
