(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear h)
		(clear n)
		(handempty)
		(on b f)
		(on c g)
		(on d o)
		(on e b)
		(on h i)
		(on i l)
		(on j m)
		(on k e)
		(on l j)
		(on m k)
		(on o a)
		(ontable a)
		(ontable f)
		(ontable g)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
