(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear i)
		(clear n)
		(handempty)
		(on a o)
		(on b h)
		(on c g)
		(on d l)
		(on f e)
		(on h f)
		(on i m)
		(on j d)
		(on k j)
		(on l c)
		(on o k)
		(ontable e)
		(ontable g)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
