(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear k)
		(clear n)
		(handempty)
		(on a l)
		(on c m)
		(on d g)
		(on e b)
		(on f j)
		(on g c)
		(on h o)
		(on i h)
		(on j i)
		(on k f)
		(on l d)
		(ontable b)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
