(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear h)
		(clear i)
		(clear k)
		(clear l)
		(handempty)
		(on a d)
		(on b n)
		(on c g)
		(on e o)
		(on g b)
		(on h j)
		(on i e)
		(on k c)
		(on m f)
		(on n m)
		(ontable d)
		(ontable f)
		(ontable j)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
