(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear l)
		(clear m)
		(clear o)
		(handempty)
		(on a i)
		(on b f)
		(on c d)
		(on d e)
		(on e g)
		(on h j)
		(on j k)
		(on k c)
		(on m n)
		(on n a)
		(on o h)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
