(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear l)
		(clear o)
		(handempty)
		(on a h)
		(on c k)
		(on d f)
		(on e b)
		(on f m)
		(on i e)
		(on j n)
		(on k j)
		(on l a)
		(on m i)
		(on n d)
		(on o g)
		(ontable b)
		(ontable g)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
