(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear e)
		(clear h)
		(clear n)
		(handempty)
		(on a d)
		(on b m)
		(on c f)
		(on f l)
		(on g j)
		(on i o)
		(on j k)
		(on k c)
		(on m a)
		(on n i)
		(on o g)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
