(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear g)
		(clear l)
		(clear n)
		(handempty)
		(on c m)
		(on d j)
		(on f k)
		(on g o)
		(on i e)
		(on l h)
		(on m f)
		(on n c)
		(on o i)
		(ontable a)
		(ontable b)
		(ontable e)
		(ontable h)
		(ontable j)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
