(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear e)
		(clear i)
		(clear n)
		(handempty)
		(on a f)
		(on b j)
		(on c g)
		(on d l)
		(on e h)
		(on f m)
		(on h o)
		(on j k)
		(on l c)
		(on m b)
		(on n a)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
