(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear f)
		(clear k)
		(clear m)
		(handempty)
		(on c g)
		(on d l)
		(on e b)
		(on f e)
		(on h i)
		(on i a)
		(on j d)
		(on k o)
		(on l c)
		(on m n)
		(on n j)
		(on o h)
		(ontable a)
		(ontable b)
		(ontable g)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
