(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear m)
		(clear n)
		(handempty)
		(on b k)
		(on c e)
		(on d o)
		(on e i)
		(on f j)
		(on g c)
		(on i h)
		(on j l)
		(on k d)
		(on n b)
		(ontable a)
		(ontable h)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
