(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear f)
		(clear i)
		(clear m)
		(handempty)
		(on a h)
		(on b n)
		(on c g)
		(on d l)
		(on e a)
		(on f o)
		(on i e)
		(on j d)
		(on l c)
		(on m k)
		(on n j)
		(on o b)
		(ontable g)
		(ontable h)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
