(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear n)
		(handempty)
		(on a d)
		(on b f)
		(on c g)
		(on d k)
		(on f o)
		(on h j)
		(on i l)
		(on j b)
		(on k h)
		(on l c)
		(on n i)
		(on o m)
		(ontable e)
		(ontable g)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
