(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(clear f)
		(clear h)
		(handempty)
		(on a m)
		(on b k)
		(on c l)
		(on f j)
		(on h i)
		(on i b)
		(on j o)
		(on k a)
		(on l g)
		(on m n)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
