(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear j)
		(clear n)
		(clear o)
		(handempty)
		(on a m)
		(on b d)
		(on c f)
		(on d c)
		(on e l)
		(on f h)
		(on g e)
		(on j k)
		(on k g)
		(on l i)
		(on m b)
		(ontable h)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
