(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear f)
		(clear g)
		(clear k)
		(handempty)
		(on a i)
		(on b l)
		(on c o)
		(on d h)
		(on f j)
		(on g e)
		(on h m)
		(on j d)
		(on k b)
		(on m n)
		(on o a)
		(ontable e)
		(ontable i)
		(ontable l)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
