(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear f)
		(clear k)
		(clear l)
		(clear m)
		(clear n)
		(handempty)
		(on a g)
		(on b i)
		(on i h)
		(on j o)
		(on k b)
		(on l j)
		(on n e)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable h)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
