(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear g)
		(clear i)
		(clear j)
		(handempty)
		(on a k)
		(on b a)
		(on d c)
		(on f o)
		(on g d)
		(on i l)
		(on j m)
		(on k f)
		(on l b)
		(on m e)
		(on n h)
		(on o n)
		(ontable c)
		(ontable e)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
