(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear f)
		(clear i)
		(clear j)
		(handempty)
		(on a e)
		(on b m)
		(on c g)
		(on e c)
		(on f k)
		(on h l)
		(on j n)
		(on k h)
		(on l d)
		(on m o)
		(ontable d)
		(ontable g)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
