(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear j)
		(handempty)
		(on a f)
		(on b e)
		(on c g)
		(on d a)
		(on e i)
		(on f m)
		(on g n)
		(on i h)
		(on j l)
		(on k c)
		(on l o)
		(on m k)
		(on n b)
		(ontable h)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
