(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear d)
		(clear l)
		(holding i)
		(on b n)
		(on c o)
		(on d a)
		(on e k)
		(on f e)
		(on g c)
		(on h f)
		(on j g)
		(on l j)
		(on m q)
		(on n m)
		(on p h)
		(on q p)
		(ontable a)
		(ontable k)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
