(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear e)
		(clear j)
		(clear n)
		(clear p)
		(clear q)
		(handempty)
		(on a h)
		(on b m)
		(on c o)
		(on d c)
		(on e f)
		(on g a)
		(on h i)
		(on i b)
		(on j g)
		(on n l)
		(on p k)
		(ontable f)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
