(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear h)
		(clear i)
		(clear n)
		(clear q)
		(handempty)
		(on a g)
		(on b o)
		(on d k)
		(on e m)
		(on g d)
		(on h j)
		(on i l)
		(on j a)
		(on l c)
		(on n e)
		(on o f)
		(on q p)
		(ontable c)
		(ontable f)
		(ontable k)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
