(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear f)
		(clear h)
		(clear i)
		(clear j)
		(clear l)
		(holding q)
		(on b a)
		(on c n)
		(on d c)
		(on e k)
		(on f e)
		(on g m)
		(on h o)
		(on i d)
		(on l p)
		(on p g)
		(ontable a)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
