(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear g)
		(clear l)
		(clear o)
		(clear q)
		(handempty)
		(on a j)
		(on b m)
		(on c h)
		(on d f)
		(on e k)
		(on g p)
		(on i b)
		(on j i)
		(on k a)
		(on l n)
		(on o c)
		(on q d)
		(ontable f)
		(ontable h)
		(ontable m)
		(ontable n)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
