(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear f)
		(clear g)
		(clear i)
		(clear j)
		(clear l)
		(handempty)
		(on a h)
		(on b d)
		(on c a)
		(on d q)
		(on e k)
		(on f e)
		(on g m)
		(on h n)
		(on i o)
		(on l b)
		(on o p)
		(on q c)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
