(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear h)
		(clear n)
		(clear p)
		(holding a)
		(on b m)
		(on c o)
		(on d l)
		(on e k)
		(on f e)
		(on g i)
		(on h c)
		(on i b)
		(on j q)
		(on l f)
		(on o g)
		(on p j)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
