(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear c)
		(clear i)
		(clear k)
		(clear q)
		(handempty)
		(on a g)
		(on b m)
		(on c d)
		(on d f)
		(on f p)
		(on g j)
		(on h n)
		(on i b)
		(on k o)
		(on l h)
		(on o e)
		(on p l)
		(ontable e)
		(ontable j)
		(ontable m)
		(ontable n)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
