(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear k)
		(clear m)
		(clear q)
		(handempty)
		(on a p)
		(on b n)
		(on c o)
		(on d c)
		(on e h)
		(on f j)
		(on g d)
		(on h i)
		(on i l)
		(on j g)
		(on q a)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
