(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear i)
		(clear j)
		(clear l)
		(clear p)
		(holding f)
		(on a g)
		(on b m)
		(on c o)
		(on d c)
		(on e a)
		(on h b)
		(on i k)
		(on j n)
		(on k e)
		(on l h)
		(on n q)
		(on q d)
		(ontable g)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
