(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear q)
		(handempty)
		(on a j)
		(on b m)
		(on c k)
		(on e l)
		(on f p)
		(on g f)
		(on h n)
		(on i b)
		(on j i)
		(on k g)
		(on l c)
		(on o h)
		(on p o)
		(on q d)
		(ontable d)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
