(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear c)
		(clear m)
		(handempty)
		(on a p)
		(on b h)
		(on c g)
		(on d l)
		(on f i)
		(on h f)
		(on i j)
		(on j e)
		(on l n)
		(on m o)
		(on n a)
		(on o d)
		(on p q)
		(on q k)
		(ontable e)
		(ontable g)
		(ontable k)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
