(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear f)
		(clear k)
		(clear m)
		(holding b)
		(on c d)
		(on d g)
		(on e o)
		(on f q)
		(on g n)
		(on i l)
		(on j c)
		(on k j)
		(on l p)
		(on o h)
		(on p e)
		(on q i)
		(ontable a)
		(ontable h)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
