(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear k)
		(clear m)
		(clear p)
		(holding b)
		(on a i)
		(on c o)
		(on d f)
		(on f e)
		(on g c)
		(on h g)
		(on i j)
		(on j h)
		(on k l)
		(on l n)
		(on p q)
		(on q d)
		(ontable e)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
