(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear l)
		(clear o)
		(clear q)
		(holding m)
		(on a n)
		(on b p)
		(on d c)
		(on e k)
		(on f e)
		(on g j)
		(on h f)
		(on i g)
		(on l i)
		(on n d)
		(on o b)
		(on p h)
		(on q a)
		(ontable c)
		(ontable j)
		(ontable k)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
