(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear b)
		(clear g)
		(clear l)
		(handempty)
		(on a f)
		(on b j)
		(on c o)
		(on d h)
		(on f i)
		(on g k)
		(on h n)
		(on i d)
		(on k e)
		(on l m)
		(on m p)
		(on p q)
		(on q c)
		(ontable e)
		(ontable j)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
