(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear f)
		(clear o)
		(clear q)
		(handempty)
		(on a j)
		(on b m)
		(on c p)
		(on d e)
		(on e l)
		(on f h)
		(on g a)
		(on i b)
		(on j i)
		(on l c)
		(on n g)
		(on o n)
		(on q k)
		(ontable h)
		(ontable k)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
