(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear h)
		(holding i)
		(on a j)
		(on b m)
		(on c o)
		(on d c)
		(on f k)
		(on g d)
		(on h n)
		(on j l)
		(on k q)
		(on n b)
		(on p g)
		(on q p)
		(ontable e)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
