(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear h)
		(clear l)
		(clear n)
		(clear o)
		(holding d)
		(on a q)
		(on b m)
		(on c p)
		(on e k)
		(on f e)
		(on g j)
		(on h i)
		(on i b)
		(on l f)
		(on n a)
		(on o g)
		(on q c)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
