(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear i)
		(clear j)
		(holding g)
		(on a q)
		(on c o)
		(on d f)
		(on e k)
		(on f l)
		(on h n)
		(on i p)
		(on j m)
		(on k d)
		(on l a)
		(on m b)
		(on o e)
		(on p c)
		(on q h)
		(ontable b)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
