(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear f)
		(clear l)
		(clear q)
		(handempty)
		(on a n)
		(on b m)
		(on c o)
		(on d c)
		(on e d)
		(on f k)
		(on g e)
		(on h i)
		(on i b)
		(on k p)
		(on n g)
		(on p h)
		(on q j)
		(ontable j)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
