(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear d)
		(clear i)
		(clear j)
		(clear m)
		(handempty)
		(on a b)
		(on b h)
		(on c p)
		(on e k)
		(on f e)
		(on g n)
		(on i c)
		(on l f)
		(on n q)
		(on o g)
		(on p o)
		(on q l)
		(ontable d)
		(ontable h)
		(ontable j)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
