(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear h)
		(clear k)
		(clear l)
		(clear n)
		(clear q)
		(holding c)
		(on a f)
		(on b m)
		(on e a)
		(on f b)
		(on g j)
		(on h d)
		(on i g)
		(on j e)
		(on l i)
		(on n o)
		(on q p)
		(ontable d)
		(ontable k)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
