(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear f)
		(clear i)
		(clear m)
		(clear n)
		(holding p)
		(on a q)
		(on c o)
		(on d c)
		(on e k)
		(on f j)
		(on g d)
		(on i l)
		(on j g)
		(on l b)
		(on m h)
		(on n a)
		(on q e)
		(ontable b)
		(ontable h)
		(ontable k)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
