(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear i)
		(clear j)
		(holding f)
		(on b m)
		(on c l)
		(on d o)
		(on e k)
		(on g h)
		(on h n)
		(on i b)
		(on j d)
		(on l g)
		(on o p)
		(on p q)
		(on q c)
		(ontable a)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
