(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear k)
		(clear m)
		(clear o)
		(handempty)
		(on a h)
		(on b c)
		(on c j)
		(on e q)
		(on f p)
		(on g b)
		(on h n)
		(on m d)
		(on o l)
		(on p g)
		(on q i)
		(ontable d)
		(ontable i)
		(ontable j)
		(ontable k)
		(ontable l)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
