(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear g)
		(clear h)
		(clear j)
		(clear p)
		(clear q)
		(holding i)
		(on a d)
		(on c o)
		(on d c)
		(on e k)
		(on f e)
		(on g l)
		(on h n)
		(on j a)
		(on l f)
		(on p b)
		(on q m)
		(ontable b)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
