(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear f)
		(clear j)
		(clear l)
		(clear q)
		(holding d)
		(on b m)
		(on c o)
		(on e n)
		(on f a)
		(on g p)
		(on h c)
		(on i b)
		(on j i)
		(on k h)
		(on l e)
		(on n g)
		(on q k)
		(ontable a)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
