(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear g)
		(clear l)
		(clear p)
		(clear q)
		(holding k)
		(on a o)
		(on b m)
		(on c f)
		(on h j)
		(on i b)
		(on j i)
		(on l h)
		(on n d)
		(on p c)
		(on q n)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
