(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear h)
		(clear m)
		(clear n)
		(clear q)
		(handempty)
		(on a d)
		(on c l)
		(on e k)
		(on f e)
		(on h o)
		(on j p)
		(on n g)
		(on o j)
		(on p i)
		(on q f)
		(ontable b)
		(ontable d)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable l)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
