(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear f)
		(clear g)
		(clear h)
		(clear i)
		(holding p)
		(on b m)
		(on c d)
		(on d n)
		(on e l)
		(on f a)
		(on g c)
		(on h o)
		(on i j)
		(on j e)
		(on l q)
		(on q k)
		(ontable a)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
