(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear k)
		(clear l)
		(clear n)
		(clear p)
		(handempty)
		(on a d)
		(on b f)
		(on c o)
		(on d c)
		(on f h)
		(on g q)
		(on h j)
		(on j g)
		(on k e)
		(on l i)
		(on p m)
		(on q a)
		(ontable e)
		(ontable i)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
