(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear g)
		(clear i)
		(handempty)
		(on a o)
		(on c h)
		(on d p)
		(on e k)
		(on f e)
		(on g n)
		(on h l)
		(on i j)
		(on j m)
		(on l f)
		(on n d)
		(on o q)
		(on p a)
		(on q c)
		(ontable b)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
