(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear i)
		(clear m)
		(clear o)
		(clear p)
		(handempty)
		(on b f)
		(on d c)
		(on e k)
		(on f n)
		(on g h)
		(on h a)
		(on i l)
		(on l q)
		(on n j)
		(on p g)
		(ontable a)
		(ontable c)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
