(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear e)
		(clear g)
		(clear n)
		(handempty)
		(on a j)
		(on b m)
		(on c l)
		(on d f)
		(on e h)
		(on h c)
		(on i b)
		(on j i)
		(on k p)
		(on l q)
		(on n o)
		(on o k)
		(on q a)
		(ontable f)
		(ontable g)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
