(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear h)
		(clear k)
		(clear p)
		(handempty)
		(on a n)
		(on b m)
		(on c f)
		(on d j)
		(on e d)
		(on f l)
		(on i b)
		(on j i)
		(on k o)
		(on l e)
		(on n q)
		(on p a)
		(on q g)
		(ontable g)
		(ontable h)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
