(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear f)
		(clear g)
		(clear h)
		(clear l)
		(holding o)
		(on a j)
		(on b m)
		(on c d)
		(on d n)
		(on e c)
		(on g q)
		(on h p)
		(on i b)
		(on j i)
		(on l k)
		(on q a)
		(ontable f)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
