(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear i)
		(clear k)
		(clear n)
		(holding o)
		(on a q)
		(on b l)
		(on c a)
		(on d f)
		(on h m)
		(on i d)
		(on j h)
		(on k p)
		(on l j)
		(on m c)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable n)
		(ontable p)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
