(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(clear q)
		(holding f)
		(on a d)
		(on b m)
		(on c l)
		(on d e)
		(on e j)
		(on g p)
		(on h n)
		(on i b)
		(on j i)
		(on l h)
		(on o k)
		(on p o)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
