DEFAULT_OUTPUT_LAYER = "unary"
DEFAULT_NUM_FOLDS = 10
DEFAULT_HIDDEN_LAYERS = 5
DEFAULT_BATCH_SIZE = 100
DEFAULT_ACTIVATION = "sigmoid"
DEFAULT_WEIGHT_DECAY = 0
DEFAULT_DROPOUT_RATE = 0
DEFAULT_SHUFFLE = False
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_MAX_EPOCHS = 1000
DEFAULT_MAX_TRAINING_TIME = 86400

DEFAULT_SEARCH_ALGORITHM = "astar"
DEFAULT_MAX_SEARCH_TIME = 1800
DEFAULT_OUTPUT_FOLDER = "./results"