(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear i)
		(clear j)
		(handempty)
		(on c k)
		(on d b)
		(on e p)
		(on f h)
		(on g l)
		(on h o)
		(on i d)
		(on k a)
		(on m g)
		(on o m)
		(on p n)
		(ontable a)
		(ontable b)
		(ontable j)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
