(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear e)
		(clear k)
		(clear o)
		(handempty)
		(on b d)
		(on c f)
		(on e l)
		(on f g)
		(on g h)
		(on i j)
		(on j n)
		(on k a)
		(on l m)
		(on m i)
		(on o p)
		(on p b)
		(ontable a)
		(ontable d)
		(ontable h)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
