(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear e)
		(clear j)
		(clear m)
		(handempty)
		(on a o)
		(on b a)
		(on c f)
		(on d n)
		(on e b)
		(on g d)
		(on i h)
		(on j g)
		(on k i)
		(on m l)
		(on n k)
		(ontable f)
		(ontable h)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
