(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear g)
		(clear o)
		(handempty)
		(on a i)
		(on b f)
		(on c e)
		(on d k)
		(on f c)
		(on g a)
		(on h l)
		(on i m)
		(on k h)
		(on l n)
		(on m d)
		(on n j)
		(ontable e)
		(ontable j)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
