(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(clear n)
		(handempty)
		(on a o)
		(on c k)
		(on d i)
		(on f b)
		(on h j)
		(on i f)
		(on j e)
		(on k h)
		(on l m)
		(on n l)
		(on o d)
		(ontable b)
		(ontable e)
		(ontable g)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
