(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear h)
		(clear o)
		(handempty)
		(on b m)
		(on c l)
		(on e k)
		(on f a)
		(on g i)
		(on h g)
		(on i f)
		(on l j)
		(on m n)
		(on o c)
		(ontable a)
		(ontable d)
		(ontable j)
		(ontable k)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
