(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear h)
		(clear m)
		(handempty)
		(on a i)
		(on b l)
		(on c b)
		(on d j)
		(on e o)
		(on g n)
		(on h k)
		(on i g)
		(on l d)
		(on n c)
		(ontable f)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
