(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear i)
		(clear m)
		(handempty)
		(on a b)
		(on b o)
		(on c g)
		(on d l)
		(on f n)
		(on h e)
		(on i h)
		(on j d)
		(on k f)
		(on l c)
		(on m k)
		(on n j)
		(ontable e)
		(ontable g)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
