(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear g)
		(clear j)
		(clear l)
		(handempty)
		(on a o)
		(on b i)
		(on d f)
		(on f h)
		(on g a)
		(on i n)
		(on j b)
		(on k e)
		(on m k)
		(on n d)
		(on o m)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
