(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear f)
		(clear l)
		(clear n)
		(handempty)
		(on a d)
		(on b a)
		(on c g)
		(on d o)
		(on f i)
		(on g m)
		(on h b)
		(on i h)
		(on j k)
		(on m j)
		(on n e)
		(ontable e)
		(ontable k)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
