(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear c)
		(clear f)
		(clear g)
		(clear n)
		(handempty)
		(on a d)
		(on b e)
		(on e o)
		(on f i)
		(on g l)
		(on h j)
		(on i k)
		(on l b)
		(on n m)
		(on o h)
		(ontable c)
		(ontable d)
		(ontable j)
		(ontable k)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
