(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear f)
		(clear j)
		(clear m)
		(handempty)
		(on a k)
		(on b i)
		(on c l)
		(on e g)
		(on f h)
		(on g d)
		(on i c)
		(on j n)
		(on k e)
		(on m o)
		(ontable d)
		(ontable h)
		(ontable l)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
