(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear h)
		(clear i)
		(clear k)
		(clear o)
		(handempty)
		(on a l)
		(on c g)
		(on d e)
		(on f m)
		(on i d)
		(on k j)
		(on l c)
		(on m n)
		(on n a)
		(on o f)
		(ontable b)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable j)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
