(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear n)
		(handempty)
		(on a o)
		(on b k)
		(on c g)
		(on d l)
		(on e m)
		(on f j)
		(on h a)
		(on i h)
		(on j d)
		(on l c)
		(on m i)
		(on n b)
		(on o f)
		(ontable g)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
