(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear c)
		(clear f)
		(clear g)
		(handempty)
		(on a j)
		(on b d)
		(on c k)
		(on d n)
		(on e h)
		(on g m)
		(on i o)
		(on j l)
		(on k a)
		(on m i)
		(on n e)
		(ontable f)
		(ontable h)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
