(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear g)
		(clear k)
		(clear l)
		(handempty)
		(on b f)
		(on d h)
		(on f m)
		(on g i)
		(on k o)
		(on l b)
		(on m e)
		(on n j)
		(on o n)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
