(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear j)
		(clear n)
		(clear o)
		(handempty)
		(on a b)
		(on c a)
		(on d f)
		(on e k)
		(on f h)
		(on i d)
		(on j g)
		(on k i)
		(on l m)
		(on m e)
		(on n c)
		(on o l)
		(ontable b)
		(ontable g)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
