(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear g)
		(clear o)
		(handempty)
		(on a k)
		(on b l)
		(on c j)
		(on d m)
		(on e b)
		(on g c)
		(on i h)
		(on j a)
		(on k d)
		(on l i)
		(on m n)
		(on o f)
		(ontable f)
		(ontable h)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
