(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear g)
		(clear j)
		(clear l)
		(handempty)
		(on a h)
		(on b k)
		(on c d)
		(on d o)
		(on e f)
		(on j i)
		(on k e)
		(on l c)
		(on m n)
		(on n a)
		(on o m)
		(ontable f)
		(ontable g)
		(ontable h)
		(ontable i)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
