(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear l)
		(clear n)
		(handempty)
		(on b g)
		(on c k)
		(on d j)
		(on h m)
		(on i b)
		(on j a)
		(on k d)
		(on l o)
		(on m i)
		(on n h)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
