(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear g)
		(clear k)
		(handempty)
		(on a i)
		(on b m)
		(on c f)
		(on d n)
		(on e o)
		(on f e)
		(on g l)
		(on i d)
		(on l h)
		(on m j)
		(ontable h)
		(ontable j)
		(ontable k)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
