(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear g)
		(handempty)
		(on b k)
		(on c n)
		(on d o)
		(on e b)
		(on g c)
		(on i h)
		(on j m)
		(on k f)
		(on l d)
		(on m i)
		(on n l)
		(on o j)
		(ontable a)
		(ontable f)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
