(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear f)
		(clear l)
		(handempty)
		(on a o)
		(on b a)
		(on c j)
		(on d n)
		(on f m)
		(on g c)
		(on h i)
		(on i k)
		(on j d)
		(on k g)
		(on l b)
		(on m h)
		(ontable e)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
