(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear j)
		(clear m)
		(clear o)
		(handempty)
		(on a n)
		(on b k)
		(on c g)
		(on d l)
		(on e h)
		(on f i)
		(on h a)
		(on j b)
		(on k d)
		(on l c)
		(on n f)
		(ontable g)
		(ontable i)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
