(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear d)
		(clear j)
		(clear m)
		(clear o)
		(handempty)
		(on b i)
		(on c k)
		(on d n)
		(on e b)
		(on f g)
		(on h e)
		(on l h)
		(on m f)
		(on n c)
		(on o l)
		(ontable a)
		(ontable g)
		(ontable i)
		(ontable j)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
