(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear m)
		(handempty)
		(on a e)
		(on b h)
		(on c k)
		(on d i)
		(on f o)
		(on g c)
		(on h l)
		(on i n)
		(on k b)
		(on l d)
		(on m j)
		(ontable e)
		(ontable j)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
