#!/bin/sh

#                          -c -D
./fast-test-original-rsl.sh 0 -1 results tasks/ferber21selected/test_states/blocks/moderate/probBLOCKS-14-0/p*.pddl #0
./fast-test-original-rsl.sh 1 -1 results tasks/ferber21selected/test_states/blocks/moderate/probBLOCKS-15-0/p*.pddl #1
./fast-test-original-rsl.sh 2 -1 results tasks/ferber21selected/test_states/blocks/moderate/probBLOCKS-15-1/p*.pddl #2
./fast-test-original-rsl.sh 3 -1 results tasks/ferber21selected/test_states/blocks/moderate/probBLOCKS-16-1/p*.pddl #3
./fast-test-original-rsl.sh 4 -1 results tasks/ferber21selected/test_states/blocks/moderate/probBLOCKS-17-0/p*.pddl #4
./fast-test-original-rsl.sh 5 -1 results tasks/ferber21selected/test_states/blocks/hard/probBLOCKS-18-4/p*.pddl #5
./fast-test-original-rsl.sh 6 -1 results tasks/ferber21selected/test_states/blocks/hard/probBLOCKS-20-1/p*.pddl #6
./fast-test-original-rsl.sh 7 -1 results tasks/ferber21selected/test_states/blocks/hard/probBLOCKS-25-2/p*.pddl #7
./fast-test-original-rsl.sh 8 -1 results tasks/ferber21selected/test_states/blocks/hard/probBLOCKS-30-1/p*.pddl #8
./fast-test-original-rsl.sh 9 -1 results tasks/ferber21selected/test_states/blocks/hard/probBLOCKS-35-2/p*.pddl #9

./fast-test-original-rsl.sh 10 -1 results tasks/ferber21selected/test_states/depot/moderate/p05/p*.pddl #10
./fast-test-original-rsl.sh 0 0 results tasks/ferber21selected/test_states/depot/moderate/p08/p*.pddl #11
./fast-test-original-rsl.sh 1 1 results tasks/ferber21selected/test_states/depot/moderate/p09/p*.pddl #12
./fast-test-original-rsl.sh 2 2 results tasks/ferber21selected/test_states/depot/moderate/p11/p*.pddl #13
./fast-test-original-rsl.sh 3 3 results tasks/ferber21selected/test_states/depot/moderate/p15/p*.pddl #14
./fast-test-original-rsl.sh 4 4 results tasks/ferber21selected/test_states/depot/moderate/p16/p*.pddl #15
./fast-test-original-rsl.sh 5 5 results tasks/ferber21selected/test_states/depot/hard/p06/p*.pddl #16
./fast-test-original-rsl.sh 6 6 results tasks/ferber21selected/test_states/depot/hard/p12/p*.pddl #17
./fast-test-original-rsl.sh 7 7 results tasks/ferber21selected/test_states/depot/hard/p14/p*.pddl #18
./fast-test-original-rsl.sh 8 8 results tasks/ferber21selected/test_states/depot/hard/p18/p*.pddl #19
./fast-test-original-rsl.sh 9 9 results tasks/ferber21selected/test_states/depot/hard/p19/p*.pddl #20
./fast-test-original-rsl.sh 10 10 results tasks/ferber21selected/test_states/depot/hard/p20/p*.pddl #21
./fast-test-original-rsl.sh 0 11 results tasks/ferber21selected/test_states/depot/hard/p22/p*.pddl #22

./fast-test-original-rsl.sh 1 12 results tasks/ferber21selected/test_states/grid/moderate/prob03_0/p*.pddl #23
./fast-test-original-rsl.sh 2 13 results tasks/ferber21selected/test_states/grid/moderate/prob04_0/p*.pddl #24
./fast-test-original-rsl.sh 3 14 results tasks/ferber21selected/test_states/grid/hard/prob04_2/p*.pddl #25
./fast-test-original-rsl.sh 4 15 results tasks/ferber21selected/test_states/grid/hard/prob04_3/p*.pddl #26
./fast-test-original-rsl.sh 5 16 results tasks/ferber21selected/test_states/grid/hard/prob04_4/p*.pddl #27
./fast-test-original-rsl.sh 6 17 results tasks/ferber21selected/test_states/grid/hard/prob05_0/p*.pddl #28
./fast-test-original-rsl.sh 7 18 results tasks/ferber21selected/test_states/grid/hard/prob05_1/p*.pddl #29
./fast-test-original-rsl.sh 8 19 results tasks/ferber21selected/test_states/grid/hard/prob05_2/p*.pddl #30
./fast-test-original-rsl.sh 9 20 results tasks/ferber21selected/test_states/grid/hard/prob05_3/p*.pddl #31
./fast-test-original-rsl.sh 10 21 results tasks/ferber21selected/test_states/grid/hard/prob05_4/p*.pddl #32

./fast-test-original-rsl.sh 0 22 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n6_1/p*.pddl #33
./fast-test-original-rsl.sh 1 23 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n6_2/p*.pddl #34
./fast-test-original-rsl.sh 2 24 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n6_3/p*.pddl #35
./fast-test-original-rsl.sh 3 25 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n6_4/p*.pddl #36
./fast-test-original-rsl.sh 4 26 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n7_1/p*.pddl #37
./fast-test-original-rsl.sh 5 27 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n7_2/p*.pddl #38
./fast-test-original-rsl.sh 6 28 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n7_3/p*.pddl #39
./fast-test-original-rsl.sh 7 29 results tasks/ferber21selected/test_states/npuzzle/moderate/prob_n7_4/p*.pddl #40
./fast-test-original-rsl.sh 8 30 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n8_1/p*.pddl #41
./fast-test-original-rsl.sh 9 31 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n8_2/p*.pddl #42
./fast-test-original-rsl.sh 10 32 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n8_3/p*.pddl #43
./fast-test-original-rsl.sh 0 33 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n8_4/p*.pddl #44
./fast-test-original-rsl.sh 1 34 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n9_1/p*.pddl #45
./fast-test-original-rsl.sh 2 35 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n9_2/p*.pddl #46
./fast-test-original-rsl.sh 3 36 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n9_3/p*.pddl #47
./fast-test-original-rsl.sh 4 37 results tasks/ferber21selected/test_states/npuzzle/hard/prob_n9_4/p*.pddl #48

./fast-test-original-rsl.sh 5 38 results tasks/ferber21selected/test_states/rovers/moderate/p11/p*.pddl #49
./fast-test-original-rsl.sh 6 39 results tasks/ferber21selected/test_states/rovers/moderate/p18/p*.pddl #50
./fast-test-original-rsl.sh 7 40 results tasks/ferber21selected/test_states/rovers/moderate/p20/p*.pddl #51
./fast-test-original-rsl.sh 8 41 results tasks/ferber21selected/test_states/rovers/moderate/p21/p*.pddl #52
./fast-test-original-rsl.sh 9 42 results tasks/ferber21selected/test_states/rovers/moderate/p22/p*.pddl #53
./fast-test-original-rsl.sh 10 43 results tasks/ferber21selected/test_states/rovers/moderate/p23/p*.pddl #54
./fast-test-original-rsl.sh 0 44 results tasks/ferber21selected/test_states/rovers/moderate/p26/p*.pddl #55
./fast-test-original-rsl.sh 1 45 results tasks/ferber21selected/test_states/rovers/moderate/p28/p*.pddl #56
./fast-test-original-rsl.sh 2 46 results tasks/ferber21selected/test_states/rovers/hard/p19/p*.pddl #57
./fast-test-original-rsl.sh 3 47 results tasks/ferber21selected/test_states/rovers/hard/p24/p*.pddl #58
./fast-test-original-rsl.sh 4 48 results tasks/ferber21selected/test_states/rovers/hard/p27/p*.pddl #59
./fast-test-original-rsl.sh 5 49 results tasks/ferber21selected/test_states/rovers/hard/p29/p*.pddl #60
./fast-test-original-rsl.sh 6 50 results tasks/ferber21selected/test_states/rovers/hard/p30/p*.pddl #61
./fast-test-original-rsl.sh 7 51 results tasks/ferber21selected/test_states/rovers/hard/p31/p*.pddl #62
./fast-test-original-rsl.sh 8 52 results tasks/ferber21selected/test_states/rovers/hard/p32/p*.pddl #63
./fast-test-original-rsl.sh 9 53 results tasks/ferber21selected/test_states/rovers/hard/p33/p*.pddl #64
./fast-test-original-rsl.sh 10 54 results tasks/ferber21selected/test_states/rovers/hard/p34/p*.pddl #65
./fast-test-original-rsl.sh 0 55 results tasks/ferber21selected/test_states/rovers/hard/p35/p*.pddl #66
./fast-test-original-rsl.sh 1 56 results tasks/ferber21selected/test_states/rovers/hard/p36/p*.pddl #67
./fast-test-original-rsl.sh 2 57 results tasks/ferber21selected/test_states/rovers/hard/p37/p*.pddl #68
./fast-test-original-rsl.sh 3 58 results tasks/ferber21selected/test_states/rovers/hard/p38/p*.pddl #69
./fast-test-original-rsl.sh 4 59 results tasks/ferber21selected/test_states/rovers/hard/p39/p*.pddl #70
./fast-test-original-rsl.sh 5 60 results tasks/ferber21selected/test_states/rovers/hard/p40/p*.pddl #71

./fast-test-original-rsl.sh 6 61 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p07/p*.pddl #72
./fast-test-original-rsl.sh 7 62 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p10/p*.pddl #73
./fast-test-original-rsl.sh 8 63 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p13/p*.pddl #74
./fast-test-original-rsl.sh 9 64 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p15/p*.pddl #75
./fast-test-original-rsl.sh 10 65 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p16/p*.pddl #76
./fast-test-original-rsl.sh 0 66 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/moderate/p20/p*.pddl #77
./fast-test-original-rsl.sh 1 67 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/hard/p17/p*.pddl #78
./fast-test-original-rsl.sh 2 68 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/hard/p18/p*.pddl #79
./fast-test-original-rsl.sh 3 69 results tasks/ferber21selected/test_states/scanalyzer-opt11-strips/hard/p19/p*.pddl #80

./fast-test-original-rsl.sh 4 70 results tasks/ferber21selected/test_states/storage/moderate/p18/p*.pddl #81
./fast-test-original-rsl.sh 5 71 results tasks/ferber21selected/test_states/storage/moderate/p20/p*.pddl #82
./fast-test-original-rsl.sh 6 72 results tasks/ferber21selected/test_states/storage/moderate/p21/p*.pddl #83
./fast-test-original-rsl.sh 7 73 results tasks/ferber21selected/test_states/storage/moderate/p23/p*.pddl #84
./fast-test-original-rsl.sh 8 74 results tasks/ferber21selected/test_states/storage/hard/p19/p*.pddl #85
./fast-test-original-rsl.sh 9 75 results tasks/ferber21selected/test_states/storage/hard/p24/p*.pddl #86
./fast-test-original-rsl.sh 10 76 results tasks/ferber21selected/test_states/storage/hard/p25/p*.pddl #87
./fast-test-original-rsl.sh 0 77 results tasks/ferber21selected/test_states/storage/hard/p26/p*.pddl #88
./fast-test-original-rsl.sh 1 78 results tasks/ferber21selected/test_states/storage/hard/p27/p*.pddl #89
./fast-test-original-rsl.sh 2 79 results tasks/ferber21selected/test_states/storage/hard/p28/p*.pddl #90
./fast-test-original-rsl.sh 3 80 results tasks/ferber21selected/test_states/storage/hard/p29/p*.pddl #91
./fast-test-original-rsl.sh 4 81 results tasks/ferber21selected/test_states/storage/hard/p30/p*.pddl #92

./fast-test-original-rsl.sh 5 82 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p10/p*.pddl #93
./fast-test-original-rsl.sh 6 83 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p11/p*.pddl #94
./fast-test-original-rsl.sh 7 84 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p12/p*.pddl #95
./fast-test-original-rsl.sh 8 85 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p16/p*.pddl #96
./fast-test-original-rsl.sh 9 86 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p17/p*.pddl #97
./fast-test-original-rsl.sh 10 87 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p18/p*.pddl #98
./fast-test-original-rsl.sh 0 88 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p19/p*.pddl #99
./fast-test-original-rsl.sh 1 89 results tasks/ferber21selected/test_states/transport-opt14-strips/moderate/p20/p*.pddl #100
./fast-test-original-rsl.sh 2 90 results tasks/ferber21selected/test_states/transport-opt14-strips/hard/p31/p*.pddl #101
./fast-test-original-rsl.sh 3 91 results tasks/ferber21selected/test_states/transport-opt14-strips/hard/p32/p*.pddl #102
./fast-test-original-rsl.sh 4 92 results tasks/ferber21selected/test_states/transport-opt14-strips/hard/p33/p*.pddl #103
./fast-test-original-rsl.sh 5 93 results tasks/ferber21selected/test_states/transport-opt14-strips/hard/p34/p*.pddl #104
./fast-test-original-rsl.sh 6 94 results tasks/ferber21selected/test_states/transport-opt14-strips/hard/p35/p*.pddl #105

./fast-test-original-rsl.sh 7 95 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-12/p*.pddl #106
./fast-test-original-rsl.sh 8 96 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-13/p*.pddl #107
./fast-test-original-rsl.sh 9 97 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-14/p*.pddl #108
./fast-test-original-rsl.sh 10 98 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-15/p*.pddl #109
./fast-test-original-rsl.sh 0 99 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-16/p*.pddl #110
./fast-test-original-rsl.sh 1 100 results tasks/ferber21selected/test_states/visitall-opt14-strips/moderate/p-1-17/p*.pddl #111
./fast-test-original-rsl.sh 2 101 results tasks/ferber21selected/test_states/visitall-opt14-strips/hard/p-1-18/p*.pddl #112

./fast-test-original-rsl.sh 3 102 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p19-net2-b18-g6/p*.pddl #113
./fast-test-original-rsl.sh 4 103 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p21-net3-b12-g2/p*.pddl #114
./fast-test-original-rsl.sh 5 104 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p27-net3-b18-g6/p*.pddl #115
./fast-test-original-rsl.sh 6 105 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p24-net3-b14-g5/p*.pddl #116
./fast-test-original-rsl.sh 7 106 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p28-net3-b18-g7/p*.pddl #117
./fast-test-original-rsl.sh 8 107 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p30-net3-b20-g8/p*.pddl #118
./fast-test-original-rsl.sh 9 108 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p31-net4-b14-g3/p*.pddl #119
./fast-test-original-rsl.sh 10 109 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p32-net4-b14-g5/p*.pddl #120
./fast-test-original-rsl.sh 0 110 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p34-net4-b16-g6/p*.pddl #121
./fast-test-original-rsl.sh 1 111 results tasks/ferber21selected/test_states/pipesworld-notankage/moderate/p41-net5-b22-g2/p*.pddl #122
./fast-test-original-rsl.sh 2 112 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p22-net3-b12-g4/p*.pddl #123
./fast-test-original-rsl.sh 3 113 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p25-net3-b16-g5/p*.pddl #124
./fast-test-original-rsl.sh 4 114 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p29-net3-b20-g6/p*.pddl #125
./fast-test-original-rsl.sh 5 115 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p26-net3-b16-g7/p*.pddl #126
./fast-test-original-rsl.sh 6 116 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p33-net4-b16-g5/p*.pddl #127
./fast-test-original-rsl.sh 7 117 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p35-net4-b18-g4/p*.pddl #128
./fast-test-original-rsl.sh 8 118 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p36-net4-b18-g6/p*.pddl #129
./fast-test-original-rsl.sh 9 119 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p37-net4-b20-g5/p*.pddl #130
./fast-test-original-rsl.sh 10 120 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p38-net4-b20-g7/p*.pddl #131
./fast-test-original-rsl.sh 0 121 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p39-net4-b22-g7/p*.pddl #132
./fast-test-original-rsl.sh 1 122 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p40-net4-b22-g8/p*.pddl #133
./fast-test-original-rsl.sh 2 123 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p42-net5-b22-g4/p*.pddl #134
./fast-test-original-rsl.sh 3 124 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p43-net5-b24-g3/p*.pddl #135
./fast-test-original-rsl.sh 4 125 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p44-net5-b24-g5/p*.pddl #136
./fast-test-original-rsl.sh 5 126 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p45-net5-b26-g4/p*.pddl #137
./fast-test-original-rsl.sh 6 127 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p46-net5-b26-g6/p*.pddl #138
./fast-test-original-rsl.sh 7 128 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p47-net5-b28-g5/p*.pddl #139
./fast-test-original-rsl.sh 8 129 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p48-net5-b28-g7/p*.pddl #140
./fast-test-original-rsl.sh 9 130 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p49-net5-b30-g6/p*.pddl #141
./fast-test-original-rsl.sh 10 131 results tasks/ferber21selected/test_states/pipesworld-notankage/hard/p50-net5-b30-g8/p*.pddl #142
