(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear m)
		(clear n)
		(handempty)
		(on b e)
		(on c b)
		(on d j)
		(on g c)
		(on h i)
		(on i g)
		(on j a)
		(on k l)
		(on l d)
		(on m h)
		(on n k)
		(ontable a)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
