(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear g)
		(clear j)
		(holding n)
		(on b e)
		(on c l)
		(on d h)
		(on f d)
		(on g i)
		(on h a)
		(on i k)
		(on j m)
		(on k c)
		(on l b)
		(ontable a)
		(ontable e)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
