(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear g)
		(clear h)
		(clear l)
		(handempty)
		(on a f)
		(on b e)
		(on c m)
		(on g i)
		(on h n)
		(on i c)
		(on j a)
		(on k b)
		(on l k)
		(on m j)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
