(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear g)
		(clear i)
		(holding c)
		(on a k)
		(on b l)
		(on d n)
		(on f a)
		(on h d)
		(on i e)
		(on j m)
		(on k j)
		(on l f)
		(on m h)
		(ontable e)
		(ontable g)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
