(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear m)
		(holding a)
		(on b l)
		(on c f)
		(on d i)
		(on f h)
		(on g d)
		(on h j)
		(on i n)
		(on l k)
		(on m g)
		(ontable e)
		(ontable j)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
