(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear b)
		(clear g)
		(clear k)
		(clear l)
		(holding e)
		(on a h)
		(on d i)
		(on f m)
		(on g d)
		(on h j)
		(on i n)
		(on k f)
		(on l c)
		(ontable b)
		(ontable c)
		(ontable j)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
