(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear g)
		(clear j)
		(clear l)
		(handempty)
		(on a f)
		(on c e)
		(on e k)
		(on f d)
		(on g m)
		(on i a)
		(on j n)
		(on k h)
		(on l b)
		(on n i)
		(ontable b)
		(ontable d)
		(ontable h)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
