(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear g)
		(clear k)
		(holding n)
		(on a f)
		(on b e)
		(on c l)
		(on d a)
		(on g h)
		(on h m)
		(on j i)
		(on k c)
		(on l b)
		(on m j)
		(ontable e)
		(ontable f)
		(ontable i)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
