(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear f)
		(clear i)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a e)
		(on c a)
		(on d n)
		(on e b)
		(on h j)
		(on j d)
		(on k g)
		(on m h)
		(ontable b)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
