(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear g)
		(clear m)
		(clear n)
		(handempty)
		(on a c)
		(on b a)
		(on c e)
		(on d l)
		(on e k)
		(on f d)
		(on j i)
		(on k h)
		(on l b)
		(on m j)
		(on n f)
		(ontable g)
		(ontable h)
		(ontable i)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
