(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear d)
		(clear i)
		(holding n)
		(on a h)
		(on b e)
		(on c m)
		(on d g)
		(on g j)
		(on i k)
		(on j f)
		(on k l)
		(on l c)
		(on m a)
		(ontable e)
		(ontable f)
		(ontable h)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
