(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear h)
		(clear k)
		(clear m)
		(handempty)
		(on b e)
		(on c l)
		(on d a)
		(on g i)
		(on h j)
		(on i d)
		(on j n)
		(on l b)
		(on m f)
		(on n g)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable k)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
