(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear f)
		(clear g)
		(clear j)
		(clear k)
		(handempty)
		(on b e)
		(on c m)
		(on d i)
		(on f h)
		(on i n)
		(on j a)
		(on k l)
		(on l b)
		(on m d)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
