(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(handempty)
		(on a g)
		(on b e)
		(on c l)
		(on d j)
		(on f m)
		(on g h)
		(on h i)
		(on i n)
		(on k c)
		(on l b)
		(on m k)
		(ontable e)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
