(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(clear j)
		(holding n)
		(on a c)
		(on b e)
		(on c m)
		(on d g)
		(on f i)
		(on g k)
		(on k h)
		(on l b)
		(on m l)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
