(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear c)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a h)
		(on b e)
		(on g b)
		(on h i)
		(on i d)
		(on j n)
		(on k j)
		(on l f)
		(on m g)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
