(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear g)
		(clear h)
		(clear j)
		(handempty)
		(on b e)
		(on c b)
		(on d i)
		(on f k)
		(on g l)
		(on h d)
		(on i n)
		(on j f)
		(on k m)
		(on l a)
		(ontable a)
		(ontable e)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
