(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear d)
		(clear g)
		(clear m)
		(holding i)
		(on a n)
		(on b e)
		(on c l)
		(on f k)
		(on g j)
		(on k c)
		(on l b)
		(on m h)
		(on n f)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
