(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear e)
		(clear j)
		(clear k)
		(clear m)
		(holding l)
		(on a f)
		(on b c)
		(on d i)
		(on e h)
		(on g a)
		(on i n)
		(on j b)
		(on k g)
		(ontable c)
		(ontable f)
		(ontable h)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
