(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(clear l)
		(handempty)
		(on c m)
		(on d h)
		(on e j)
		(on f g)
		(on g a)
		(on h b)
		(on i n)
		(on j f)
		(on l k)
		(on m i)
		(ontable a)
		(ontable b)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
