(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear h)
		(clear j)
		(clear m)
		(holding b)
		(on a g)
		(on c d)
		(on d i)
		(on e k)
		(on g f)
		(on h e)
		(on i n)
		(on j c)
		(on m l)
		(ontable f)
		(ontable k)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
