(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear e)
		(clear h)
		(clear l)
		(holding i)
		(on a f)
		(on c b)
		(on d n)
		(on e m)
		(on g d)
		(on h g)
		(on j a)
		(on l k)
		(on n j)
		(ontable b)
		(ontable f)
		(ontable k)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
