(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear h)
		(clear l)
		(holding j)
		(on a i)
		(on c m)
		(on e c)
		(on g k)
		(on h g)
		(on i n)
		(on l b)
		(on m d)
		(ontable b)
		(ontable d)
		(ontable f)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
