(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear m)
		(holding l)
		(on a d)
		(on b e)
		(on c k)
		(on d f)
		(on f g)
		(on h n)
		(on i j)
		(on j a)
		(on k b)
		(on m h)
		(on n i)
		(ontable e)
		(ontable g)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
