(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear f)
		(clear n)
		(handempty)
		(on a g)
		(on b e)
		(on c i)
		(on f m)
		(on g d)
		(on h j)
		(on i k)
		(on k a)
		(on l b)
		(on m h)
		(on n l)
		(ontable d)
		(ontable e)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
