(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear h)
		(holding j)
		(on a k)
		(on b e)
		(on c l)
		(on d i)
		(on f g)
		(on g d)
		(on h f)
		(on i n)
		(on k m)
		(on l b)
		(on m c)
		(ontable e)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
