(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear d)
		(clear i)
		(clear m)
		(clear p)
		(holding g)
		(on c k)
		(on d c)
		(on f o)
		(on h e)
		(on j l)
		(on k a)
		(on l f)
		(on m h)
		(on n j)
		(on p n)
		(ontable a)
		(ontable b)
		(ontable e)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
