(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear c)
		(clear h)
		(handempty)
		(on b i)
		(on c k)
		(on d l)
		(on e m)
		(on g f)
		(on h d)
		(on i n)
		(on j p)
		(on k a)
		(on l e)
		(on m o)
		(on n g)
		(on o j)
		(ontable a)
		(ontable f)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
