(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear i)
		(clear m)
		(clear n)
		(holding b)
		(on c k)
		(on d c)
		(on f j)
		(on g f)
		(on i l)
		(on j o)
		(on k a)
		(on l e)
		(on m g)
		(on n p)
		(on o h)
		(ontable a)
		(ontable e)
		(ontable h)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
