(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear d)
		(clear j)
		(clear p)
		(holding n)
		(on c k)
		(on d c)
		(on f e)
		(on g f)
		(on h i)
		(on j h)
		(on k a)
		(on l g)
		(on m o)
		(on o l)
		(on p m)
		(ontable a)
		(ontable b)
		(ontable e)
		(ontable i)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
