(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear g)
		(clear m)
		(clear o)
		(clear p)
		(holding l)
		(on b d)
		(on c k)
		(on d c)
		(on e n)
		(on f e)
		(on h j)
		(on i b)
		(on j i)
		(on k a)
		(on n h)
		(on o f)
		(ontable a)
		(ontable g)
		(ontable m)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
