(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear f)
		(clear h)
		(clear l)
		(clear o)
		(clear p)
		(handempty)
		(on b n)
		(on c k)
		(on d i)
		(on f e)
		(on h c)
		(on k a)
		(on l b)
		(on n m)
		(on o g)
		(on p j)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable j)
		(ontable m)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
