(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear f)
		(clear i)
		(clear n)
		(handempty)
		(on b k)
		(on c b)
		(on d p)
		(on f o)
		(on g j)
		(on h e)
		(on i d)
		(on k a)
		(on l h)
		(on m l)
		(on n g)
		(on o m)
		(ontable a)
		(ontable e)
		(ontable j)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
