(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(holding a)
		(on b c)
		(on c i)
		(on d k)
		(on e h)
		(on h o)
		(on i n)
		(on j m)
		(on k b)
		(on l j)
		(on m p)
		(on n l)
		(on o g)
		(ontable f)
		(ontable g)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
