(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear f)
		(clear h)
		(clear j)
		(clear l)
		(clear n)
		(holding p)
		(on b d)
		(on c k)
		(on d c)
		(on f o)
		(on i b)
		(on k a)
		(on l m)
		(on m e)
		(on n i)
		(on o g)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable j)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
