(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear d)
		(clear j)
		(clear l)
		(clear m)
		(clear o)
		(handempty)
		(on b i)
		(on c k)
		(on d p)
		(on e c)
		(on f e)
		(on i n)
		(on j f)
		(on k a)
		(on m h)
		(on o g)
		(ontable a)
		(ontable g)
		(ontable h)
		(ontable l)
		(ontable n)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
