(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear e)
		(clear h)
		(clear i)
		(clear m)
		(holding j)
		(on b f)
		(on c b)
		(on d n)
		(on e c)
		(on f l)
		(on g o)
		(on h k)
		(on i g)
		(on k a)
		(on m p)
		(ontable a)
		(ontable l)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
