(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear e)
		(clear f)
		(clear h)
		(clear j)
		(clear m)
		(clear p)
		(handempty)
		(on c k)
		(on d c)
		(on f l)
		(on h o)
		(on i n)
		(on j b)
		(on k a)
		(on l d)
		(on m i)
		(on o g)
		(ontable a)
		(ontable b)
		(ontable e)
		(ontable g)
		(ontable n)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
