(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear n)
		(clear p)
		(handempty)
		(on b d)
		(on c k)
		(on d j)
		(on e i)
		(on h f)
		(on j c)
		(on k a)
		(on l o)
		(on m h)
		(on o m)
		(on p l)
		(ontable a)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
