(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear j)
		(clear k)
		(holding n)
		(on a h)
		(on b d)
		(on c p)
		(on d i)
		(on e b)
		(on f o)
		(on g m)
		(on h g)
		(on i l)
		(on j c)
		(on k e)
		(on l f)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
