(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear h)
		(clear k)
		(clear l)
		(clear m)
		(holding a)
		(on b j)
		(on d c)
		(on f n)
		(on h e)
		(on j d)
		(on k o)
		(on l p)
		(on m g)
		(on n i)
		(on p f)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
