(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear i)
		(clear j)
		(clear l)
		(holding p)
		(on b m)
		(on c f)
		(on d k)
		(on e d)
		(on f b)
		(on i c)
		(on j e)
		(on k a)
		(on l n)
		(on m o)
		(on n h)
		(on o g)
		(ontable a)
		(ontable g)
		(ontable h)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
