(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear j)
		(handempty)
		(on a d)
		(on b n)
		(on c b)
		(on d p)
		(on e l)
		(on h o)
		(on i e)
		(on j c)
		(on k i)
		(on l f)
		(on m h)
		(on n m)
		(on o g)
		(on p k)
		(ontable f)
		(ontable g)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
