(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear e)
		(clear f)
		(clear h)
		(clear m)
		(clear o)
		(clear p)
		(holding j)
		(on b d)
		(on c k)
		(on d c)
		(on i b)
		(on k a)
		(on m l)
		(on n i)
		(on o g)
		(on p n)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable h)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
