(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear h)
		(clear k)
		(clear m)
		(holding d)
		(on b e)
		(on e c)
		(on f o)
		(on h l)
		(on j f)
		(on k a)
		(on l n)
		(on m i)
		(on n p)
		(on o g)
		(on p j)
		(ontable a)
		(ontable c)
		(ontable g)
		(ontable i)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
