(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear f)
		(clear n)
		(clear o)
		(clear p)
		(handempty)
		(on a g)
		(on b c)
		(on c d)
		(on d i)
		(on e h)
		(on f k)
		(on g l)
		(on i j)
		(on m b)
		(on n m)
		(on p e)
		(ontable h)
		(ontable j)
		(ontable k)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
