(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear f)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on b n)
		(on d c)
		(on f i)
		(on g h)
		(on h e)
		(on i m)
		(on j o)
		(on m g)
		(on n p)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable k)
		(ontable l)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
