(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear g)
		(clear h)
		(clear o)
		(handempty)
		(on a p)
		(on b i)
		(on c d)
		(on d f)
		(on f n)
		(on g k)
		(on h b)
		(on j a)
		(on k j)
		(on n m)
		(on o e)
		(on p l)
		(ontable e)
		(ontable i)
		(ontable l)
		(ontable m)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
