(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear g)
		(clear i)
		(clear m)
		(holding d)
		(on a n)
		(on c f)
		(on e l)
		(on f k)
		(on h p)
		(on i h)
		(on j e)
		(on k a)
		(on m c)
		(on o j)
		(on p o)
		(ontable b)
		(ontable g)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
