(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear g)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a d)
		(on b h)
		(on c b)
		(on d c)
		(on f p)
		(on h i)
		(on i n)
		(on k f)
		(on l a)
		(on n o)
		(on o j)
		(on p e)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable m)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
