(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear f)
		(clear j)
		(clear l)
		(clear o)
		(handempty)
		(on b p)
		(on c i)
		(on d k)
		(on e m)
		(on f b)
		(on g n)
		(on h e)
		(on j h)
		(on k a)
		(on l c)
		(on p g)
		(ontable a)
		(ontable i)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
