(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear i)
		(clear j)
		(clear o)
		(holding b)
		(on a n)
		(on c f)
		(on g h)
		(on h e)
		(on j k)
		(on k p)
		(on l g)
		(on m a)
		(on n d)
		(on o l)
		(on p m)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable i)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
