(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear g)
		(clear j)
		(clear l)
		(handempty)
		(on a h)
		(on b k)
		(on c e)
		(on e a)
		(on f d)
		(on g b)
		(on i f)
		(on k i)
		(ontable d)
		(ontable h)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
