(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear i)
		(clear j)
		(clear l)
		(handempty)
		(on a k)
		(on d f)
		(on g d)
		(on i c)
		(on j a)
		(on k h)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
