(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear g)
		(clear j)
		(clear l)
		(handempty)
		(on a e)
		(on d k)
		(on f i)
		(on g h)
		(on i c)
		(on j f)
		(on l a)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
