(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear k)
		(clear l)
		(handempty)
		(on a h)
		(on b c)
		(on c d)
		(on d i)
		(on e b)
		(on g j)
		(on k g)
		(ontable f)
		(ontable h)
		(ontable i)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
