(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear l)
		(handempty)
		(on a g)
		(on b k)
		(on c a)
		(on e d)
		(on f j)
		(on g h)
		(on h i)
		(on i b)
		(on k e)
		(on l c)
		(ontable d)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
