(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear h)
		(clear j)
		(handempty)
		(on a f)
		(on b d)
		(on d i)
		(on e b)
		(on f k)
		(on g a)
		(on h l)
		(on i c)
		(on k e)
		(on l g)
		(ontable c)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
