(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear i)
		(clear l)
		(handempty)
		(on a g)
		(on b f)
		(on d j)
		(on e h)
		(on f k)
		(on i c)
		(on k a)
		(on l e)
		(ontable c)
		(ontable g)
		(ontable h)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
