(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear f)
		(clear g)
		(handempty)
		(on b k)
		(on d i)
		(on e j)
		(on f d)
		(on g b)
		(on h l)
		(on i c)
		(on j a)
		(on k h)
		(ontable a)
		(ontable c)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
