(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear g)
		(clear i)
		(clear l)
		(holding j)
		(on a e)
		(on b f)
		(on d b)
		(on e h)
		(on f a)
		(on i c)
		(on k d)
		(on l k)
		(ontable c)
		(ontable g)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
