(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear e)
		(clear g)
		(clear i)
		(handempty)
		(on b a)
		(on c d)
		(on d j)
		(on e f)
		(on f h)
		(on g b)
		(on h k)
		(on j l)
		(ontable a)
		(ontable i)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
