(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear h)
		(clear j)
		(handempty)
		(on a f)
		(on b d)
		(on d i)
		(on e l)
		(on g b)
		(on h e)
		(on i c)
		(on j k)
		(on k a)
		(on l g)
		(ontable c)
		(ontable f)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
