(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear g)
		(clear j)
		(clear l)
		(holding b)
		(on d i)
		(on f k)
		(on g f)
		(on i c)
		(on j h)
		(on k e)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
