(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear d)
		(clear i)
		(clear j)
		(handempty)
		(on b h)
		(on c f)
		(on d b)
		(on e l)
		(on g a)
		(on h k)
		(on i g)
		(on k e)
		(ontable a)
		(ontable f)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
