(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear f)
		(clear h)
		(clear i)
		(clear j)
		(handempty)
		(on d k)
		(on e l)
		(on f d)
		(on g a)
		(on l g)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable h)
		(ontable i)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
