(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear e)
		(holding h)
		(on a k)
		(on b d)
		(on d i)
		(on e b)
		(on f l)
		(on g f)
		(on i c)
		(on k g)
		(on l j)
		(ontable c)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
