(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear j)
		(holding k)
		(on a h)
		(on b l)
		(on d i)
		(on e d)
		(on g e)
		(on h f)
		(on i c)
		(on j g)
		(on l a)
		(ontable c)
		(ontable f)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
