(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear g)
		(clear k)
		(clear l)
		(holding h)
		(on b e)
		(on e a)
		(on g j)
		(on i c)
		(on j f)
		(on k i)
		(ontable a)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
