(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear k)
		(holding i)
		(on a g)
		(on b f)
		(on c d)
		(on d e)
		(on g l)
		(on j h)
		(on k j)
		(ontable e)
		(ontable f)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
