(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear f)
		(clear k)
		(handempty)
		(on a g)
		(on b d)
		(on d i)
		(on e j)
		(on f l)
		(on g h)
		(on i c)
		(on j a)
		(on l b)
		(ontable c)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
