(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear h)
		(clear j)
		(clear l)
		(holding a)
		(on b g)
		(on e d)
		(on h b)
		(on i c)
		(on j k)
		(on k i)
		(on l f)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
