(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(handempty)
		(on a k)
		(on b a)
		(on d i)
		(on e l)
		(on f h)
		(on g j)
		(on h e)
		(on i c)
		(on j b)
		(on k d)
		(on l g)
		(ontable c)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
