(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear g)
		(clear j)
		(holding d)
		(on a i)
		(on c a)
		(on e k)
		(on g e)
		(on h l)
		(on j h)
		(on k b)
		(on l f)
		(ontable b)
		(ontable f)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
