(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear i)
		(clear l)
		(holding e)
		(on a k)
		(on b a)
		(on c j)
		(on d g)
		(on g h)
		(on h f)
		(on i c)
		(on j d)
		(on l b)
		(ontable f)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
