(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear j)
		(holding h)
		(on c f)
		(on d g)
		(on e b)
		(on g k)
		(on i e)
		(on j l)
		(on l i)
		(ontable a)
		(ontable b)
		(ontable f)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
