(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear i)
		(clear l)
		(holding j)
		(on a k)
		(on b g)
		(on d e)
		(on e h)
		(on h c)
		(on k f)
		(ontable c)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
