(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear h)
		(clear j)
		(clear k)
		(handempty)
		(on a b)
		(on b g)
		(on c l)
		(on e i)
		(on h e)
		(on i c)
		(on l f)
		(ontable d)
		(ontable f)
		(ontable g)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
