(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear g)
		(holding e)
		(on a i)
		(on b f)
		(on c k)
		(on d l)
		(on f a)
		(on g b)
		(on i d)
		(on j h)
		(on l j)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
