(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear g)
		(clear h)
		(clear j)
		(clear l)
		(holding e)
		(on d i)
		(on h k)
		(on k c)
		(on l f)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
