(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear i)
		(handempty)
		(on a l)
		(on b k)
		(on c h)
		(on d j)
		(on f b)
		(on i g)
		(on j f)
		(on k e)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
