(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear i)
		(clear j)
		(handempty)
		(on a e)
		(on b h)
		(on e g)
		(on f k)
		(on h d)
		(on i f)
		(on j l)
		(on l a)
		(ontable c)
		(ontable d)
		(ontable g)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
