(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear l)
		(holding a)
		(on b d)
		(on d i)
		(on e b)
		(on f k)
		(on g e)
		(on i c)
		(on j h)
		(on k g)
		(on l j)
		(ontable c)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
