(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(handempty)
		(on b d)
		(on c i)
		(on d k)
		(on e f)
		(on g l)
		(on h a)
		(on i h)
		(on k c)
		(on l j)
		(ontable a)
		(ontable f)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
