(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear g)
		(clear i)
		(handempty)
		(on a b)
		(on b f)
		(on c e)
		(on d j)
		(on e l)
		(on g c)
		(on h k)
		(on i d)
		(on j h)
		(ontable f)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
