(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(clear j)
		(clear k)
		(holding b)
		(on a g)
		(on d i)
		(on f l)
		(on h e)
		(on i c)
		(on k h)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
