(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear g)
		(clear h)
		(clear j)
		(handempty)
		(on a k)
		(on b i)
		(on d c)
		(on e b)
		(on f l)
		(on g f)
		(on i d)
		(on j e)
		(on l a)
		(ontable c)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
