(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear i)
		(clear l)
		(holding g)
		(on a h)
		(on b k)
		(on d b)
		(on f j)
		(on i c)
		(on k f)
		(on l a)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
