(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear h)
		(clear j)
		(handempty)
		(on a e)
		(on b k)
		(on d i)
		(on f b)
		(on g f)
		(on h g)
		(on i c)
		(on j l)
		(on k d)
		(ontable c)
		(ontable e)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
