(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear e)
		(clear f)
		(clear l)
		(holding i)
		(on a b)
		(on d g)
		(on f k)
		(on h j)
		(on l h)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
