(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear e)
		(clear j)
		(clear l)
		(holding h)
		(on e g)
		(on g k)
		(on i c)
		(on j f)
		(on k i)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
