(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear f)
		(handempty)
		(on a j)
		(on b d)
		(on d i)
		(on e l)
		(on f k)
		(on g b)
		(on h g)
		(on i c)
		(on j e)
		(on l h)
		(ontable c)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
