(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear h)
		(clear j)
		(handempty)
		(on b g)
		(on d b)
		(on e d)
		(on f l)
		(on g a)
		(on h f)
		(on i k)
		(on j i)
		(on k e)
		(on l c)
		(ontable a)
		(ontable c)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
