(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear g)
		(clear h)
		(clear j)
		(handempty)
		(on a f)
		(on b i)
		(on c k)
		(on f b)
		(on g c)
		(on h l)
		(on i d)
		(on j e)
		(ontable d)
		(ontable e)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
