(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(clear i)
		(clear k)
		(clear l)
		(clear q)
		(holding c)
		(on d p)
		(on e a)
		(on f m)
		(on g n)
		(on l b)
		(on m g)
		(on n j)
		(on o h)
		(on p o)
		(ontable a)
		(ontable b)
		(ontable h)
		(ontable i)
		(ontable j)
		(ontable k)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
