(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear h)
		(clear k)
		(clear l)
		(handempty)
		(on a p)
		(on b e)
		(on c o)
		(on d c)
		(on e n)
		(on f j)
		(on g d)
		(on h i)
		(on j b)
		(on k q)
		(on l f)
		(on p g)
		(on q m)
		(ontable i)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
