(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear l)
		(clear o)
		(handempty)
		(on a e)
		(on b i)
		(on c k)
		(on d n)
		(on e f)
		(on g h)
		(on h p)
		(on i m)
		(on j d)
		(on k j)
		(on l b)
		(on n g)
		(on o q)
		(on q c)
		(ontable f)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
