(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear f)
		(clear h)
		(handempty)
		(on a l)
		(on b m)
		(on c o)
		(on d c)
		(on e j)
		(on f q)
		(on g d)
		(on h p)
		(on i e)
		(on j k)
		(on k b)
		(on l i)
		(on n a)
		(on p n)
		(on q g)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
