(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear k)
		(clear o)
		(handempty)
		(on a j)
		(on b m)
		(on c p)
		(on e f)
		(on f n)
		(on g c)
		(on h l)
		(on i b)
		(on j i)
		(on k e)
		(on l q)
		(on o g)
		(on p h)
		(on q a)
		(ontable d)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
