(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear m)
		(clear q)
		(holding b)
		(on a p)
		(on c h)
		(on d g)
		(on e k)
		(on f e)
		(on g l)
		(on h o)
		(on i j)
		(on j c)
		(on l f)
		(on m i)
		(on o a)
		(on p d)
		(on q n)
		(ontable k)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
