(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear i)
		(clear j)
		(clear k)
		(clear n)
		(handempty)
		(on a e)
		(on b p)
		(on c m)
		(on d f)
		(on e o)
		(on f q)
		(on h a)
		(on i h)
		(on j l)
		(on k c)
		(on l g)
		(on o d)
		(ontable g)
		(ontable m)
		(ontable n)
		(ontable p)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
