(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear p)
		(clear q)
		(holding a)
		(on b m)
		(on c k)
		(on d i)
		(on e j)
		(on f g)
		(on g l)
		(on h n)
		(on i b)
		(on j o)
		(on k e)
		(on l h)
		(on o f)
		(on p c)
		(ontable m)
		(ontable n)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
