(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(clear q)
		(handempty)
		(on a d)
		(on b n)
		(on c i)
		(on d m)
		(on e k)
		(on f e)
		(on g f)
		(on h p)
		(on i o)
		(on j b)
		(on l h)
		(on o j)
		(on q l)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
