(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear h)
		(clear m)
		(clear q)
		(holding n)
		(on a o)
		(on b j)
		(on c l)
		(on e k)
		(on f e)
		(on g i)
		(on h g)
		(on i a)
		(on l f)
		(on m b)
		(on o d)
		(on q p)
		(ontable d)
		(ontable j)
		(ontable k)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
