(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(handempty)
		(on a p)
		(on b m)
		(on c q)
		(on e o)
		(on f h)
		(on g i)
		(on h l)
		(on i j)
		(on j n)
		(on k b)
		(on l a)
		(on m g)
		(on o k)
		(on q f)
		(ontable d)
		(ontable n)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
