(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear g)
		(clear i)
		(clear j)
		(clear p)
		(handempty)
		(on a q)
		(on b m)
		(on c a)
		(on d e)
		(on e h)
		(on f o)
		(on h k)
		(on i b)
		(on j f)
		(on k l)
		(on l n)
		(on o c)
		(on p d)
		(ontable g)
		(ontable m)
		(ontable n)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
