(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear d)
		(clear g)
		(clear h)
		(clear l)
		(clear p)
		(holding i)
		(on a q)
		(on b m)
		(on c o)
		(on e n)
		(on f a)
		(on g f)
		(on h j)
		(on j k)
		(on l c)
		(on p e)
		(ontable d)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
