(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear i)
		(holding b)
		(on a p)
		(on c k)
		(on d n)
		(on f j)
		(on g d)
		(on i m)
		(on j l)
		(on k o)
		(on l a)
		(on n h)
		(on o q)
		(on p g)
		(ontable e)
		(ontable h)
		(ontable m)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
