(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear c)
		(clear d)
		(clear i)
		(clear p)
		(holding e)
		(on b m)
		(on c g)
		(on d q)
		(on f h)
		(on g n)
		(on h l)
		(on i o)
		(on l k)
		(on m f)
		(on n a)
		(on p j)
		(ontable a)
		(ontable j)
		(ontable k)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
