(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(clear l)
		(handempty)
		(on b m)
		(on c o)
		(on d n)
		(on e a)
		(on f k)
		(on g h)
		(on h j)
		(on i b)
		(on j i)
		(on k c)
		(on l p)
		(on n q)
		(on q g)
		(ontable a)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
