(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear f)
		(clear h)
		(clear p)
		(holding q)
		(on a j)
		(on b m)
		(on c o)
		(on d k)
		(on e a)
		(on g n)
		(on i b)
		(on j i)
		(on k g)
		(on l c)
		(on n e)
		(on p l)
		(ontable f)
		(ontable h)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
