(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear i)
		(clear l)
		(clear q)
		(holding n)
		(on a d)
		(on b a)
		(on c o)
		(on d c)
		(on e m)
		(on f e)
		(on h j)
		(on i k)
		(on j b)
		(on k f)
		(on l p)
		(on m h)
		(on p g)
		(ontable g)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
