(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear g)
		(clear j)
		(clear o)
		(clear p)
		(handempty)
		(on a b)
		(on b m)
		(on d a)
		(on e k)
		(on f e)
		(on h q)
		(on j n)
		(on l f)
		(on n h)
		(on o c)
		(on p i)
		(on q l)
		(ontable c)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
