(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear d)
		(clear g)
		(clear p)
		(handempty)
		(on a q)
		(on b m)
		(on c l)
		(on e k)
		(on f b)
		(on g e)
		(on i f)
		(on j a)
		(on l o)
		(on n j)
		(on o n)
		(on p i)
		(on q h)
		(ontable d)
		(ontable h)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
