(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear g)
		(clear h)
		(clear o)
		(clear p)
		(handempty)
		(on a j)
		(on b m)
		(on e k)
		(on g q)
		(on h l)
		(on j b)
		(on l i)
		(on n d)
		(on p a)
		(on q n)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
