(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear d)
		(clear k)
		(clear o)
		(handempty)
		(on a l)
		(on b m)
		(on c q)
		(on d p)
		(on e f)
		(on g h)
		(on h n)
		(on i b)
		(on j i)
		(on l e)
		(on o g)
		(on p j)
		(on q a)
		(ontable f)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
