(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear k)
		(clear l)
		(clear m)
		(holding p)
		(on a q)
		(on b i)
		(on c d)
		(on d j)
		(on e f)
		(on f a)
		(on g n)
		(on h o)
		(on i h)
		(on j g)
		(on m c)
		(on n b)
		(ontable k)
		(ontable l)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
