(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear i)
		(clear j)
		(holding k)
		(on a e)
		(on b m)
		(on c o)
		(on d c)
		(on e n)
		(on f a)
		(on g d)
		(on i q)
		(on j p)
		(on l g)
		(on n h)
		(on p l)
		(on q f)
		(ontable h)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
