(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear c)
		(clear g)
		(clear i)
		(clear l)
		(clear q)
		(handempty)
		(on a e)
		(on c o)
		(on d h)
		(on e k)
		(on f j)
		(on g n)
		(on h a)
		(on i f)
		(on j p)
		(on m d)
		(on n m)
		(ontable b)
		(ontable k)
		(ontable l)
		(ontable o)
		(ontable p)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
