(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear g)
		(clear i)
		(clear j)
		(clear o)
		(handempty)
		(on a n)
		(on b m)
		(on c h)
		(on d l)
		(on e k)
		(on f a)
		(on g f)
		(on i b)
		(on j c)
		(on l p)
		(on n q)
		(on q e)
		(ontable h)
		(ontable k)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
