(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear k)
		(clear l)
		(handempty)
		(on a q)
		(on b m)
		(on c o)
		(on d a)
		(on e c)
		(on f d)
		(on g j)
		(on h n)
		(on i b)
		(on j h)
		(on k p)
		(on l f)
		(on p g)
		(on q i)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
