(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear h)
		(clear k)
		(clear l)
		(holding q)
		(on a p)
		(on b m)
		(on c g)
		(on e j)
		(on g d)
		(on h a)
		(on j i)
		(on l n)
		(on o c)
		(on p o)
		(ontable d)
		(ontable f)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
