(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear g)
		(clear h)
		(clear j)
		(clear k)
		(clear n)
		(holding f)
		(on a i)
		(on b c)
		(on c p)
		(on d o)
		(on g q)
		(on j m)
		(on l d)
		(on m b)
		(on q l)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable k)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
