(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear h)
		(clear i)
		(clear j)
		(clear n)
		(holding m)
		(on a g)
		(on b a)
		(on c o)
		(on d e)
		(on e k)
		(on g f)
		(on i l)
		(on j c)
		(on n q)
		(on o d)
		(on q p)
		(ontable f)
		(ontable h)
		(ontable k)
		(ontable l)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
