(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear f)
		(clear l)
		(holding c)
		(on a j)
		(on b m)
		(on d g)
		(on e o)
		(on f k)
		(on g q)
		(on h e)
		(on i b)
		(on j i)
		(on k p)
		(on o n)
		(on p h)
		(on q a)
		(ontable l)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
