(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear g)
		(clear h)
		(holding n)
		(on a j)
		(on b m)
		(on c f)
		(on d c)
		(on f k)
		(on g l)
		(on h o)
		(on i b)
		(on j i)
		(on k p)
		(on l q)
		(on p e)
		(on q a)
		(ontable e)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
