(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on a d)
		(on b m)
		(on c o)
		(on d c)
		(on e f)
		(on f a)
		(on g e)
		(on i b)
		(on j i)
		(on k p)
		(on l j)
		(on n q)
		(on p h)
		(on q g)
		(ontable h)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
