(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear h)
		(clear j)
		(clear k)
		(handempty)
		(on a o)
		(on b m)
		(on c n)
		(on e g)
		(on h q)
		(on i b)
		(on j i)
		(on l p)
		(on n l)
		(on o c)
		(on p d)
		(ontable d)
		(ontable f)
		(ontable g)
		(ontable k)
		(ontable m)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
