(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear h)
		(clear m)
		(clear o)
		(holding d)
		(on b f)
		(on c n)
		(on e k)
		(on f e)
		(on g q)
		(on h g)
		(on j i)
		(on l j)
		(on m b)
		(on n p)
		(on p l)
		(on q c)
		(ontable a)
		(ontable i)
		(ontable k)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
