(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear d)
		(clear n)
		(holding g)
		(on a j)
		(on b m)
		(on c e)
		(on d f)
		(on e k)
		(on i b)
		(on j i)
		(on k o)
		(on l q)
		(on n p)
		(on o h)
		(on p l)
		(on q a)
		(ontable f)
		(ontable h)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
