(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear b)
		(clear j)
		(clear l)
		(handempty)
		(on a k)
		(on b n)
		(on c o)
		(on d c)
		(on e i)
		(on f h)
		(on g d)
		(on i p)
		(on j q)
		(on k m)
		(on n e)
		(on p f)
		(on q g)
		(ontable h)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
