(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear h)
		(clear l)
		(clear q)
		(holding n)
		(on b m)
		(on c a)
		(on d g)
		(on e k)
		(on f e)
		(on h o)
		(on i b)
		(on j i)
		(on l j)
		(on o f)
		(on p d)
		(on q p)
		(ontable a)
		(ontable g)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
