(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear i)
		(clear l)
		(clear p)
		(holding k)
		(on a q)
		(on b m)
		(on c o)
		(on d c)
		(on f h)
		(on g d)
		(on h n)
		(on i b)
		(on l g)
		(on p j)
		(ontable e)
		(ontable j)
		(ontable m)
		(ontable n)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
