(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear g)
		(clear k)
		(clear l)
		(clear p)
		(handempty)
		(on a h)
		(on b m)
		(on e j)
		(on f n)
		(on g i)
		(on h f)
		(on i b)
		(on j q)
		(on k a)
		(on l d)
		(on n e)
		(on p o)
		(on q c)
		(ontable c)
		(ontable d)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
