(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear f)
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on b q)
		(on c o)
		(on d c)
		(on e j)
		(on f e)
		(on g d)
		(on h g)
		(on j a)
		(on k b)
		(on l m)
		(on m p)
		(on p h)
		(on q i)
		(ontable a)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
