(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear d)
		(clear h)
		(clear i)
		(clear j)
		(clear o)
		(handempty)
		(on a g)
		(on b m)
		(on d b)
		(on e k)
		(on f n)
		(on g e)
		(on h q)
		(on j l)
		(on l a)
		(on o c)
		(on p f)
		(on q p)
		(ontable c)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
