(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear h)
		(clear i)
		(clear n)
		(clear q)
		(holding l)
		(on a j)
		(on b m)
		(on c o)
		(on d c)
		(on e k)
		(on g d)
		(on h a)
		(on i e)
		(on j g)
		(on n p)
		(on p f)
		(ontable f)
		(ontable k)
		(ontable m)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
