(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear j)
		(clear l)
		(clear o)
		(handempty)
		(on a q)
		(on b m)
		(on c i)
		(on d h)
		(on e k)
		(on h p)
		(on i d)
		(on l c)
		(on n e)
		(on o b)
		(on p n)
		(ontable f)
		(ontable g)
		(ontable j)
		(ontable k)
		(ontable m)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
