(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on a j)
		(on b m)
		(on c o)
		(on d f)
		(on e g)
		(on g d)
		(on h e)
		(on i b)
		(on j i)
		(on k h)
		(on l q)
		(on p a)
		(on q p)
		(ontable f)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
