(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear f)
		(clear j)
		(clear l)
		(holding a)
		(on b m)
		(on c o)
		(on d q)
		(on e k)
		(on f e)
		(on g d)
		(on h n)
		(on i b)
		(on j i)
		(on l p)
		(on p g)
		(on q h)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
