(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear b)
		(clear i)
		(handempty)
		(on a f)
		(on b p)
		(on c o)
		(on d c)
		(on e k)
		(on f e)
		(on g d)
		(on h n)
		(on i m)
		(on j g)
		(on l q)
		(on m l)
		(on p h)
		(on q j)
		(ontable k)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
