(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear j)
		(clear l)
		(clear o)
		(holding n)
		(on a h)
		(on b m)
		(on c d)
		(on d i)
		(on e k)
		(on f e)
		(on g b)
		(on h c)
		(on i g)
		(on l p)
		(on m q)
		(on q f)
		(ontable j)
		(ontable k)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
