(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on b e)
		(on d f)
		(on f g)
		(on g a)
		(on h d)
		(on i m)
		(on j h)
		(on k n)
		(on l b)
		(on n i)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
