(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear k)
		(handempty)
		(on a i)
		(on b l)
		(on d a)
		(on f j)
		(on g d)
		(on h f)
		(on i n)
		(on j g)
		(on k m)
		(on m h)
		(ontable c)
		(ontable e)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
