(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear h)
		(clear i)
		(clear j)
		(clear k)
		(clear m)
		(holding f)
		(on a l)
		(on b e)
		(on g d)
		(on h n)
		(on i a)
		(on j g)
		(on k c)
		(on l b)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
