(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear h)
		(clear m)
		(clear n)
		(holding j)
		(on a i)
		(on b e)
		(on c l)
		(on f d)
		(on i f)
		(on k c)
		(on l b)
		(on m k)
		(on n g)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable h)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
