(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear m)
		(handempty)
		(on a f)
		(on b h)
		(on c k)
		(on d i)
		(on e c)
		(on f g)
		(on g d)
		(on h a)
		(on i n)
		(on j l)
		(on k b)
		(on l e)
		(on m j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
