(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear b)
		(clear e)
		(clear f)
		(clear h)
		(holding n)
		(on c k)
		(on d i)
		(on f d)
		(on g c)
		(on h l)
		(on i g)
		(on k m)
		(on l j)
		(ontable a)
		(ontable b)
		(ontable e)
		(ontable j)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
