(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear h)
		(clear k)
		(handempty)
		(on a n)
		(on b e)
		(on c l)
		(on f i)
		(on g f)
		(on i a)
		(on j g)
		(on k m)
		(on m j)
		(on n d)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable l)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
