(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear k)
		(clear m)
		(handempty)
		(on a i)
		(on b l)
		(on c j)
		(on d g)
		(on f d)
		(on h n)
		(on i f)
		(on k h)
		(on m e)
		(on n a)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable l)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
