(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear g)
		(clear h)
		(clear j)
		(clear l)
		(clear m)
		(handempty)
		(on b e)
		(on d c)
		(on f i)
		(on g f)
		(on i n)
		(on k a)
		(on l b)
		(on m k)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
