(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear b)
		(clear i)
		(clear k)
		(holding f)
		(on a e)
		(on b h)
		(on c j)
		(on d g)
		(on e l)
		(on h m)
		(on i c)
		(on j n)
		(on m d)
		(ontable g)
		(ontable k)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
