(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear h)
		(holding a)
		(on b m)
		(on c e)
		(on d i)
		(on e k)
		(on f b)
		(on g d)
		(on h f)
		(on i n)
		(on j g)
		(on l j)
		(on m l)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
