(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear e)
		(clear i)
		(holding d)
		(on a j)
		(on b l)
		(on c k)
		(on e g)
		(on g m)
		(on h a)
		(on i n)
		(on k f)
		(on l h)
		(on m c)
		(ontable f)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
