(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear i)
		(clear l)
		(clear n)
		(handempty)
		(on b e)
		(on c f)
		(on g k)
		(on h a)
		(on i d)
		(on j h)
		(on k j)
		(on l c)
		(on m g)
		(on n m)
		(ontable a)
		(ontable d)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
