(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear f)
		(clear i)
		(clear n)
		(holding g)
		(on b e)
		(on c j)
		(on d l)
		(on f h)
		(on h m)
		(on j a)
		(on l b)
		(on n k)
		(ontable a)
		(ontable e)
		(ontable i)
		(ontable k)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
