(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear h)
		(clear i)
		(clear m)
		(holding k)
		(on b e)
		(on c l)
		(on d g)
		(on g j)
		(on h a)
		(on i c)
		(on j f)
		(on l b)
		(on m n)
		(on n d)
		(ontable a)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
