(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear e)
		(clear h)
		(clear k)
		(holding j)
		(on a f)
		(on b g)
		(on c d)
		(on g c)
		(on h l)
		(on i n)
		(on k a)
		(on l m)
		(on m i)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
