(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear i)
		(clear l)
		(handempty)
		(on a m)
		(on b e)
		(on c a)
		(on g j)
		(on h f)
		(on i k)
		(on k n)
		(on l g)
		(on m h)
		(on n d)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
