(define (problem blocks-7-0)
(:domain blocks)
(:objects c f a b g d e )
(:init
	(clear a)
	(clear b)
	(clear c)
	(handempty)
	(on b f)
	(on c g)
	(on f d)
	(on g e)
	(ontable a)
	(ontable d)
	(ontable e)
)
(:goal (and (on a g) (on g d) (on d b) (on b c) (on c f) (on f e)))
)
