(define (problem blocks-7-0)
(:domain blocks)
(:objects c f a b g d e )
(:init
	(clear d)
	(handempty)
	(on a f)
	(on c b)
	(on d g)
	(on e a)
	(on f c)
	(on g e)
	(ontable b)
)
(:goal (and (on a g) (on g d) (on d b) (on b c) (on c f) (on f e)))
)
