(define (problem blocks-7-0)
(:domain blocks)
(:objects c f a b g d e )
(:init
	(clear c)
	(clear e)
	(clear g)
	(handempty)
	(on a d)
	(on b a)
	(on f b)
	(on g f)
	(ontable c)
	(ontable d)
	(ontable e)
)
(:goal (and (on a g) (on g d) (on d b) (on b c) (on c f) (on f e)))
)
