(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear e)
		(clear h)
		(clear i)
		(clear j)
		(clear m)
		(handempty)
		(on b l)
		(on c k)
		(on d c)
		(on e n)
		(on g f)
		(on j o)
		(on k a)
		(on l g)
		(on o p)
		(on p d)
		(ontable a)
		(ontable f)
		(ontable h)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
