(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear c)
		(clear d)
		(clear g)
		(handempty)
		(on a m)
		(on b n)
		(on c o)
		(on d a)
		(on f l)
		(on g h)
		(on h j)
		(on j i)
		(on k e)
		(on n f)
		(on o k)
		(ontable e)
		(ontable i)
		(ontable l)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
