(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear h)
		(clear k)
		(clear m)
		(clear o)
		(handempty)
		(on a n)
		(on b j)
		(on c g)
		(on d l)
		(on e c)
		(on f d)
		(on j i)
		(on k b)
		(on l e)
		(on n f)
		(on o a)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
