(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear e)
		(clear f)
		(handempty)
		(on a o)
		(on b k)
		(on c l)
		(on e n)
		(on f h)
		(on g b)
		(on h c)
		(on j i)
		(on k j)
		(on l m)
		(on o g)
		(ontable d)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
