(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear j)
		(handempty)
		(on b f)
		(on c d)
		(on d e)
		(on e l)
		(on f o)
		(on h m)
		(on j b)
		(on k h)
		(on l n)
		(on m g)
		(on n i)
		(on o k)
		(ontable a)
		(ontable g)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
