(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear f)
		(clear k)
		(clear m)
		(handempty)
		(on b j)
		(on c n)
		(on d h)
		(on e o)
		(on f e)
		(on j i)
		(on k a)
		(on l g)
		(on m d)
		(on n l)
		(on o c)
		(ontable a)
		(ontable g)
		(ontable h)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
