(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear e)
		(clear k)
		(clear l)
		(clear o)
		(handempty)
		(on a n)
		(on c h)
		(on d m)
		(on e a)
		(on f j)
		(on h d)
		(on j i)
		(on k c)
		(on l g)
		(on o f)
		(ontable b)
		(ontable g)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
