(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear e)
		(clear m)
		(handempty)
		(on a c)
		(on b j)
		(on c o)
		(on d l)
		(on e f)
		(on f h)
		(on h b)
		(on j i)
		(on m n)
		(on n k)
		(on o g)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
