(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear g)
		(clear h)
		(clear o)
		(handempty)
		(on a n)
		(on b j)
		(on c d)
		(on d f)
		(on e c)
		(on f a)
		(on h k)
		(on j i)
		(on k b)
		(on m l)
		(on n m)
		(on o e)
		(ontable g)
		(ontable i)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
