(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear g)
		(clear j)
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on b d)
		(on d f)
		(on f m)
		(on g c)
		(on h a)
		(on i e)
		(on j i)
		(on k b)
		(on m o)
		(on o h)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
