(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear l)
		(clear n)
		(handempty)
		(on a c)
		(on b j)
		(on c d)
		(on d h)
		(on e a)
		(on f g)
		(on g o)
		(on h f)
		(on j i)
		(on k b)
		(on l k)
		(on o m)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
