(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear m)
		(handempty)
		(on a o)
		(on b j)
		(on c g)
		(on d e)
		(on e h)
		(on h n)
		(on j i)
		(on k l)
		(on l c)
		(on m k)
		(on n f)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
