(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear e)
		(clear g)
		(clear h)
		(clear l)
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on d f)
		(on f c)
		(on h d)
		(on j i)
		(on k b)
		(on n m)
		(on o n)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable l)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
