(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear l)
		(handempty)
		(on a n)
		(on b j)
		(on d o)
		(on f g)
		(on g d)
		(on j i)
		(on k b)
		(on l m)
		(on m a)
		(on n h)
		(on o k)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
