(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear m)
		(clear n)
		(handempty)
		(on a f)
		(on b j)
		(on c h)
		(on d o)
		(on e g)
		(on f c)
		(on h l)
		(on j i)
		(on k b)
		(on l e)
		(on o k)
		(ontable g)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
