(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear g)
		(clear h)
		(clear l)
		(clear m)
		(handempty)
		(on a f)
		(on b k)
		(on d c)
		(on f n)
		(on g e)
		(on h o)
		(on j i)
		(on k j)
		(ontable c)
		(ontable e)
		(ontable i)
		(ontable l)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
