(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear i)
		(handempty)
		(on a g)
		(on b n)
		(on c j)
		(on d h)
		(on e f)
		(on f l)
		(on g e)
		(on h m)
		(on j o)
		(on k d)
		(on n k)
		(ontable i)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
