(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear e)
		(clear h)
		(clear j)
		(handempty)
		(on c n)
		(on d i)
		(on e c)
		(on f d)
		(on h f)
		(on i a)
		(on j k)
		(on l o)
		(on m l)
		(on n m)
		(on o g)
		(ontable a)
		(ontable b)
		(ontable g)
		(ontable k)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
