(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear f)
		(clear g)
		(clear n)
		(handempty)
		(on a k)
		(on b j)
		(on d h)
		(on f o)
		(on g d)
		(on h m)
		(on j i)
		(on k b)
		(on m e)
		(on o l)
		(ontable c)
		(ontable e)
		(ontable i)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
