(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear f)
		(clear g)
		(clear h)
		(clear m)
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on d a)
		(on g c)
		(on h l)
		(on j i)
		(on k b)
		(on l d)
		(on m n)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
