(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear f)
		(clear k)
		(clear m)
		(clear o)
		(handempty)
		(on a c)
		(on b j)
		(on c l)
		(on d e)
		(on e n)
		(on f g)
		(on g h)
		(on h a)
		(on j i)
		(on l d)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
