(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear e)
		(clear h)
		(handempty)
		(on a c)
		(on b j)
		(on c g)
		(on e n)
		(on f o)
		(on g m)
		(on h d)
		(on j i)
		(on k b)
		(on l f)
		(on m l)
		(on n k)
		(ontable d)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
