(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear k)
		(handempty)
		(on a h)
		(on b j)
		(on c n)
		(on d f)
		(on e g)
		(on f e)
		(on g m)
		(on j i)
		(on k b)
		(on l c)
		(on m o)
		(on o l)
		(ontable h)
		(ontable i)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
