(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear h)
		(clear i)
		(clear k)
		(clear l)
		(clear m)
		(clear o)
		(handempty)
		(on a j)
		(on c f)
		(on e d)
		(on f g)
		(on g e)
		(on i b)
		(on j n)
		(on k c)
		(on m a)
		(ontable b)
		(ontable d)
		(ontable h)
		(ontable l)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
