(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear h)
		(clear j)
		(clear k)
		(handempty)
		(on a d)
		(on b i)
		(on c g)
		(on d n)
		(on e m)
		(on g a)
		(on h c)
		(on i e)
		(on j o)
		(on l f)
		(on n l)
		(ontable f)
		(ontable k)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
