(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear h)
		(clear i)
		(clear l)
		(clear n)
		(clear o)
		(handempty)
		(on a k)
		(on c b)
		(on d a)
		(on f g)
		(on g m)
		(on h j)
		(on i e)
		(on k c)
		(on l f)
		(ontable b)
		(ontable e)
		(ontable j)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
