(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear e)
		(clear h)
		(clear k)
		(clear o)
		(handempty)
		(on a i)
		(on c g)
		(on d b)
		(on e c)
		(on g m)
		(on h j)
		(on j f)
		(on k a)
		(on m l)
		(on o n)
		(ontable b)
		(ontable f)
		(ontable i)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
