(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear k)
		(handempty)
		(on a m)
		(on b j)
		(on d o)
		(on e d)
		(on f n)
		(on h l)
		(on j i)
		(on k a)
		(on m f)
		(on n c)
		(on o h)
		(ontable c)
		(ontable g)
		(ontable i)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
