(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear f)
		(clear i)
		(handempty)
		(on a g)
		(on c a)
		(on d m)
		(on e k)
		(on f j)
		(on g d)
		(on h l)
		(on i c)
		(on j b)
		(on k o)
		(on m n)
		(on n h)
		(ontable b)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
