(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear e)
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on a d)
		(on c j)
		(on e g)
		(on g f)
		(on i h)
		(on j a)
		(on k c)
		(on l o)
		(on n i)
		(on o m)
		(ontable b)
		(ontable d)
		(ontable f)
		(ontable h)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
