(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear j)
		(handempty)
		(on b f)
		(on d i)
		(on e k)
		(on f e)
		(on g n)
		(on h g)
		(on i b)
		(on j o)
		(on k h)
		(on l m)
		(on n l)
		(ontable a)
		(ontable c)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
