(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear l)
		(clear m)
		(clear n)
		(handempty)
		(on a d)
		(on b a)
		(on d h)
		(on e f)
		(on g j)
		(on h e)
		(on i k)
		(on j o)
		(on l g)
		(on n b)
		(on o i)
		(ontable c)
		(ontable f)
		(ontable k)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
