(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(handempty)
		(on a f)
		(on b k)
		(on c m)
		(on d h)
		(on e n)
		(on f o)
		(on g j)
		(on i c)
		(on j l)
		(on k i)
		(on m e)
		(on n g)
		(on o d)
		(ontable h)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
