(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear f)
		(clear j)
		(clear l)
		(clear m)
		(handempty)
		(on a e)
		(on c i)
		(on d n)
		(on e d)
		(on g o)
		(on h k)
		(on i b)
		(on j h)
		(on k a)
		(on l c)
		(on m g)
		(ontable b)
		(ontable f)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
