(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear c)
		(clear d)
		(clear j)
		(clear n)
		(clear o)
		(handempty)
		(on a k)
		(on c g)
		(on d i)
		(on e l)
		(on g m)
		(on h e)
		(on j a)
		(on k h)
		(on o f)
		(ontable b)
		(ontable f)
		(ontable i)
		(ontable l)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
