(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear k)
		(handempty)
		(on a o)
		(on b j)
		(on f h)
		(on g e)
		(on h l)
		(on j i)
		(on k b)
		(on l d)
		(on m n)
		(on n c)
		(on o m)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
