(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear k)
		(clear o)
		(handempty)
		(on a e)
		(on b j)
		(on c l)
		(on d n)
		(on f g)
		(on j i)
		(on k h)
		(on l m)
		(on m f)
		(on n c)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
