(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear f)
		(clear i)
		(clear j)
		(clear k)
		(clear m)
		(handempty)
		(on a n)
		(on b o)
		(on c l)
		(on d h)
		(on f e)
		(on h c)
		(on j b)
		(on m g)
		(on n d)
		(on o a)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
