(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear g)
		(clear j)
		(handempty)
		(on b f)
		(on c a)
		(on d o)
		(on e i)
		(on g k)
		(on h m)
		(on i l)
		(on j d)
		(on k e)
		(on l b)
		(on m n)
		(on o h)
		(ontable a)
		(ontable f)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
