(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear g)
		(clear h)
		(clear i)
		(handempty)
		(on b e)
		(on d n)
		(on f a)
		(on g k)
		(on h l)
		(on i j)
		(on j o)
		(on k b)
		(on m f)
		(on n m)
		(on o c)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
