(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear i)
		(clear j)
		(handempty)
		(on a h)
		(on c l)
		(on e n)
		(on f c)
		(on g o)
		(on h e)
		(on i k)
		(on j d)
		(on k a)
		(on l g)
		(on n f)
		(on o m)
		(ontable b)
		(ontable d)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
