(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear f)
		(clear k)
		(clear n)
		(holding e)
		(on a p)
		(on b l)
		(on c o)
		(on d c)
		(on f q)
		(on g d)
		(on i g)
		(on j a)
		(on m j)
		(on n m)
		(on p h)
		(on q i)
		(ontable h)
		(ontable k)
		(ontable l)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
