(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear j)
		(clear m)
		(clear p)
		(handempty)
		(on a l)
		(on b h)
		(on c o)
		(on d c)
		(on e f)
		(on f n)
		(on g d)
		(on h i)
		(on i a)
		(on j q)
		(on k e)
		(on m k)
		(on p b)
		(on q g)
		(ontable l)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
