(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear h)
		(clear m)
		(clear q)
		(holding i)
		(on c a)
		(on d o)
		(on e k)
		(on f e)
		(on g c)
		(on h p)
		(on l f)
		(on m j)
		(on n l)
		(on o g)
		(on p d)
		(on q n)
		(ontable a)
		(ontable b)
		(ontable j)
		(ontable k)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
