(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear f)
		(clear j)
		(clear m)
		(clear o)
		(handempty)
		(on a h)
		(on b a)
		(on c i)
		(on d p)
		(on e k)
		(on f e)
		(on g q)
		(on h g)
		(on i b)
		(on j d)
		(on l n)
		(on q l)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
