(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear e)
		(clear g)
		(clear i)
		(clear n)
		(handempty)
		(on a p)
		(on b h)
		(on c o)
		(on d k)
		(on e a)
		(on f l)
		(on h j)
		(on i b)
		(on j d)
		(on n m)
		(on p q)
		(on q f)
		(ontable g)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
