(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear k)
		(clear l)
		(holding f)
		(on a j)
		(on b m)
		(on c o)
		(on d q)
		(on g d)
		(on h g)
		(on i b)
		(on j i)
		(on k c)
		(on l e)
		(on n h)
		(on o p)
		(on p n)
		(on q a)
		(ontable e)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
