(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear g)
		(clear h)
		(clear k)
		(holding c)
		(on a j)
		(on b e)
		(on f b)
		(on g i)
		(on h f)
		(on i m)
		(on k n)
		(on l a)
		(on m l)
		(ontable d)
		(ontable e)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
