(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear g)
		(clear h)
		(clear l)
		(handempty)
		(on a i)
		(on b e)
		(on d k)
		(on f n)
		(on g d)
		(on h m)
		(on i c)
		(on j a)
		(on k f)
		(on l j)
		(ontable c)
		(ontable e)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
