(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear l)
		(clear m)
		(holding c)
		(on b e)
		(on d n)
		(on f k)
		(on h j)
		(on i d)
		(on j i)
		(on k h)
		(on l b)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
