(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear h)
		(clear k)
		(clear m)
		(holding a)
		(on b e)
		(on c l)
		(on d j)
		(on f i)
		(on h g)
		(on k c)
		(on l b)
		(on m n)
		(on n d)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
