(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear i)
		(holding j)
		(on a f)
		(on b e)
		(on c l)
		(on d g)
		(on f n)
		(on g k)
		(on h d)
		(on i a)
		(on k m)
		(on l b)
		(on m c)
		(on n h)
		(ontable e)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
