(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear c)
		(clear i)
		(clear l)
		(holding e)
		(on a j)
		(on b g)
		(on c f)
		(on d m)
		(on g h)
		(on i k)
		(on j n)
		(on l b)
		(on n d)
		(ontable f)
		(ontable h)
		(ontable k)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
