(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear i)
		(clear j)
		(clear k)
		(clear m)
		(handempty)
		(on a d)
		(on b e)
		(on c l)
		(on g h)
		(on i f)
		(on j g)
		(on k c)
		(on l b)
		(on m n)
		(on n a)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable h)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
