(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear h)
		(clear i)
		(clear k)
		(holding m)
		(on a g)
		(on c n)
		(on d a)
		(on e l)
		(on f d)
		(on g j)
		(on h b)
		(on i e)
		(on l c)
		(ontable b)
		(ontable j)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
