(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear e)
		(clear i)
		(clear l)
		(holding c)
		(on a f)
		(on d k)
		(on g a)
		(on h m)
		(on i b)
		(on j n)
		(on k h)
		(on l d)
		(on m j)
		(on n g)
		(ontable b)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
