(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear h)
		(clear i)
		(clear k)
		(handempty)
		(on a g)
		(on b e)
		(on c l)
		(on d m)
		(on f d)
		(on g j)
		(on h f)
		(on i n)
		(on k a)
		(on l b)
		(ontable e)
		(ontable j)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
