(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear k)
		(clear l)
		(holding m)
		(on a h)
		(on b g)
		(on f j)
		(on g a)
		(on h d)
		(on i n)
		(on k f)
		(on l i)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
