(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear k)
		(clear l)
		(holding e)
		(on a j)
		(on b c)
		(on c m)
		(on d i)
		(on f g)
		(on g d)
		(on h a)
		(on i n)
		(on k h)
		(on l f)
		(ontable j)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
