(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear i)
		(clear k)
		(clear l)
		(clear m)
		(holding c)
		(on b e)
		(on d g)
		(on h n)
		(on i j)
		(on j h)
		(on k d)
		(on l b)
		(on m a)
		(on n f)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable g)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
