(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear g)
		(clear n)
		(handempty)
		(on a j)
		(on b e)
		(on c l)
		(on d h)
		(on f m)
		(on g i)
		(on h a)
		(on j f)
		(on k c)
		(on l b)
		(on m k)
		(ontable e)
		(ontable i)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
