(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear l)
		(holding a)
		(on b c)
		(on d m)
		(on e i)
		(on f e)
		(on g h)
		(on h j)
		(on i n)
		(on k d)
		(on l b)
		(on m g)
		(on n k)
		(ontable c)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
