(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear k)
		(clear n)
		(holding d)
		(on b e)
		(on c l)
		(on f i)
		(on g c)
		(on h g)
		(on i j)
		(on j m)
		(on l b)
		(on m h)
		(ontable a)
		(ontable e)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
