(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear g)
		(clear h)
		(clear i)
		(handempty)
		(on a n)
		(on b e)
		(on c l)
		(on g k)
		(on h f)
		(on i j)
		(on j m)
		(on k c)
		(on l b)
		(on m d)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
