(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear k)
		(clear l)
		(handempty)
		(on b e)
		(on c i)
		(on d n)
		(on h f)
		(on i j)
		(on j a)
		(on k m)
		(on l g)
		(on m h)
		(on n b)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable g)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
