(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear n)
		(holding j)
		(on a h)
		(on b e)
		(on c l)
		(on f m)
		(on g c)
		(on h d)
		(on l b)
		(on m i)
		(on n k)
		(ontable d)
		(ontable e)
		(ontable i)
		(ontable k)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
