(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear h)
		(clear k)
		(clear l)
		(holding g)
		(on a j)
		(on b e)
		(on c i)
		(on d c)
		(on i n)
		(on l m)
		(on m a)
		(ontable e)
		(ontable f)
		(ontable h)
		(ontable j)
		(ontable k)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
