(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear h)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a j)
		(on b e)
		(on c d)
		(on g f)
		(on h a)
		(on i n)
		(on j i)
		(on k g)
		(on m c)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
