(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear b)
		(clear f)
		(clear h)
		(clear l)
		(clear m)
		(handempty)
		(on a j)
		(on b e)
		(on c k)
		(on d i)
		(on g d)
		(on i n)
		(on j g)
		(on l c)
		(ontable e)
		(ontable f)
		(ontable h)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
