(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear i)
		(clear k)
		(clear l)
		(handempty)
		(on b e)
		(on c j)
		(on d a)
		(on f h)
		(on g d)
		(on i g)
		(on j n)
		(on k c)
		(on l f)
		(on n m)
		(ontable a)
		(ontable e)
		(ontable h)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
