(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a c)
		(on b e)
		(on c h)
		(on d i)
		(on f b)
		(on g j)
		(on i n)
		(on k d)
		(on l g)
		(ontable e)
		(ontable h)
		(ontable j)
		(ontable m)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
