(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear d)
		(clear f)
		(clear i)
		(clear k)
		(handempty)
		(on b e)
		(on c b)
		(on f m)
		(on g n)
		(on h l)
		(on i g)
		(on k a)
		(on l c)
		(on m j)
		(on n h)
		(ontable a)
		(ontable d)
		(ontable e)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
