(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear e)
		(clear k)
		(handempty)
		(on a b)
		(on b f)
		(on c g)
		(on d i)
		(on e l)
		(on f c)
		(on g d)
		(on i n)
		(on j m)
		(on k j)
		(on m h)
		(ontable h)
		(ontable l)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
