(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear i)
		(holding c)
		(on a j)
		(on b l)
		(on d k)
		(on e d)
		(on g f)
		(on i n)
		(on k a)
		(on l m)
		(on m h)
		(ontable f)
		(ontable h)
		(ontable j)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
