(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear f)
		(clear k)
		(clear l)
		(clear n)
		(handempty)
		(on a b)
		(on b e)
		(on c i)
		(on d a)
		(on e m)
		(on f h)
		(on g j)
		(on i g)
		(on m c)
		(on n d)
		(ontable h)
		(ontable j)
		(ontable k)
		(ontable l)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
