(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear l)
		(clear m)
		(holding j)
		(on a k)
		(on b e)
		(on d n)
		(on g i)
		(on h d)
		(on i h)
		(on k g)
		(on l c)
		(on m b)
		(on n f)
		(ontable c)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
