(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear g)
		(clear k)
		(handempty)
		(on a d)
		(on b e)
		(on c m)
		(on d c)
		(on f n)
		(on g a)
		(on h f)
		(on i j)
		(on k l)
		(on m h)
		(on n i)
		(ontable e)
		(ontable j)
		(ontable l)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
