(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear g)
		(clear j)
		(clear n)
		(handempty)
		(on a f)
		(on b m)
		(on c e)
		(on d i)
		(on e b)
		(on f c)
		(on h l)
		(on k d)
		(on l a)
		(on m k)
		(on n h)
		(ontable g)
		(ontable i)
		(ontable j)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
