(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear e)
		(clear i)
		(clear n)
		(handempty)
		(on a f)
		(on c k)
		(on d h)
		(on e b)
		(on g l)
		(on h j)
		(on i d)
		(on j a)
		(on l m)
		(on m c)
		(on n g)
		(ontable b)
		(ontable f)
		(ontable k)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
