(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear g)
		(clear k)
		(clear l)
		(handempty)
		(on a m)
		(on b e)
		(on c f)
		(on f n)
		(on h i)
		(on j h)
		(on l b)
		(on m j)
		(on n a)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable k)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
