(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear h)
		(handempty)
		(on b e)
		(on c l)
		(on d i)
		(on f j)
		(on g k)
		(on h n)
		(on i m)
		(on j d)
		(on k c)
		(on l b)
		(on n g)
		(ontable a)
		(ontable e)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
