(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(clear n)
		(handempty)
		(on b a)
		(on c g)
		(on e m)
		(on h l)
		(on i f)
		(on j k)
		(on k i)
		(on l j)
		(on m h)
		(on n b)
		(ontable a)
		(ontable d)
		(ontable f)
		(ontable g)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
