(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear d)
		(clear h)
		(holding j)
		(on a g)
		(on b e)
		(on c l)
		(on d n)
		(on f c)
		(on h i)
		(on k f)
		(on l b)
		(on m k)
		(on n m)
		(ontable e)
		(ontable g)
		(ontable i)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
