(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear e)
		(clear k)
		(handempty)
		(on a d)
		(on b h)
		(on c l)
		(on d i)
		(on e m)
		(on g n)
		(on h g)
		(on i j)
		(on j f)
		(on k c)
		(on l b)
		(on n a)
		(ontable f)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
