(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear k)
		(holding g)
		(on b e)
		(on c l)
		(on d m)
		(on f a)
		(on i j)
		(on j f)
		(on k n)
		(on l b)
		(on m i)
		(on n h)
		(ontable a)
		(ontable e)
		(ontable h)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
