(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear a)
		(clear f)
		(clear i)
		(clear k)
		(clear n)
		(handempty)
		(on b e)
		(on g d)
		(on h l)
		(on i j)
		(on j g)
		(on k h)
		(on l b)
		(on m c)
		(on n m)
		(ontable a)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable f)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
