(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear d)
		(clear k)
		(handempty)
		(on b i)
		(on c n)
		(on d b)
		(on e o)
		(on f h)
		(on h l)
		(on i p)
		(on j m)
		(on k a)
		(on m f)
		(on n e)
		(on o g)
		(on p j)
		(ontable a)
		(ontable g)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
