(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear i)
		(clear l)
		(clear m)
		(clear n)
		(clear o)
		(holding j)
		(on b d)
		(on c k)
		(on d c)
		(on e h)
		(on g b)
		(on i p)
		(on k a)
		(on m g)
		(on n e)
		(on o f)
		(ontable a)
		(ontable f)
		(ontable h)
		(ontable l)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
