(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear g)
		(clear n)
		(holding b)
		(on c k)
		(on d c)
		(on e h)
		(on g m)
		(on h f)
		(on j o)
		(on k a)
		(on l p)
		(on m j)
		(on n i)
		(on o l)
		(on p e)
		(ontable a)
		(ontable f)
		(ontable i)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
