(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear d)
		(clear f)
		(clear j)
		(clear l)
		(clear p)
		(handempty)
		(on c i)
		(on d k)
		(on e o)
		(on f h)
		(on i b)
		(on k a)
		(on l m)
		(on n e)
		(on o g)
		(on p n)
		(ontable a)
		(ontable b)
		(ontable g)
		(ontable h)
		(ontable j)
		(ontable m)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
