(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear e)
		(clear i)
		(clear n)
		(holding h)
		(on b o)
		(on c j)
		(on d p)
		(on e f)
		(on g k)
		(on i g)
		(on j m)
		(on k a)
		(on m l)
		(on n b)
		(on p c)
		(ontable a)
		(ontable f)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
