(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear g)
		(clear h)
		(clear j)
		(clear m)
		(clear p)
		(holding l)
		(on b i)
		(on c a)
		(on d n)
		(on e o)
		(on g e)
		(on h c)
		(on i d)
		(on j k)
		(on m f)
		(ontable a)
		(ontable f)
		(ontable k)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
