(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear h)
		(clear l)
		(holding i)
		(on b d)
		(on c k)
		(on d c)
		(on e g)
		(on f j)
		(on j e)
		(on k a)
		(on l n)
		(on m p)
		(on n o)
		(on o m)
		(on p f)
		(ontable a)
		(ontable g)
		(ontable h)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
