(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear i)
		(clear m)
		(clear o)
		(holding h)
		(on b e)
		(on c k)
		(on d g)
		(on e f)
		(on f p)
		(on i c)
		(on j l)
		(on k a)
		(on m n)
		(on n b)
		(on p j)
		(ontable a)
		(ontable g)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
