(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(clear f)
		(clear g)
		(clear m)
		(clear n)
		(holding k)
		(on d l)
		(on f p)
		(on g i)
		(on h e)
		(on j b)
		(on l j)
		(on n o)
		(on o h)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable i)
		(ontable m)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
