(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear p)
		(handempty)
		(on b l)
		(on c k)
		(on d i)
		(on f h)
		(on h o)
		(on i j)
		(on j n)
		(on k a)
		(on m f)
		(on n m)
		(on o g)
		(on p d)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
