(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear k)
		(clear m)
		(clear p)
		(holding c)
		(on b g)
		(on e d)
		(on g i)
		(on h f)
		(on i l)
		(on j b)
		(on k a)
		(on l h)
		(on m n)
		(on n j)
		(on o e)
		(on p o)
		(ontable a)
		(ontable d)
		(ontable f)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
