(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear h)
		(clear i)
		(clear m)
		(holding j)
		(on b p)
		(on c k)
		(on d g)
		(on g l)
		(on h c)
		(on k a)
		(on l e)
		(on m o)
		(on n f)
		(on o d)
		(on p n)
		(ontable a)
		(ontable e)
		(ontable f)
		(ontable i)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
