(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear d)
		(clear f)
		(clear h)
		(clear j)
		(clear m)
		(handempty)
		(on b i)
		(on c p)
		(on d n)
		(on f g)
		(on g o)
		(on j k)
		(on k b)
		(on m l)
		(on n a)
		(on p e)
		(ontable a)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
