(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear e)
		(clear l)
		(holding n)
		(on b d)
		(on c k)
		(on d c)
		(on e o)
		(on f p)
		(on h m)
		(on i b)
		(on j i)
		(on k a)
		(on l f)
		(on m g)
		(on o h)
		(on p j)
		(ontable a)
		(ontable g)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
