(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear h)
		(clear k)
		(handempty)
		(on a o)
		(on b f)
		(on c l)
		(on d g)
		(on e j)
		(on f n)
		(on h a)
		(on j i)
		(on k m)
		(on l d)
		(on m b)
		(on n c)
		(ontable g)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
