(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear f)
		(clear i)
		(clear j)
		(clear m)
		(handempty)
		(on a k)
		(on c o)
		(on f b)
		(on h e)
		(on i a)
		(on k n)
		(on l g)
		(on m d)
		(on n h)
		(on o l)
		(ontable b)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable j)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
