(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(clear k)
		(handempty)
		(on a o)
		(on b j)
		(on c h)
		(on d a)
		(on e l)
		(on f g)
		(on h n)
		(on j i)
		(on l b)
		(on m f)
		(on o m)
		(ontable g)
		(ontable i)
		(ontable k)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
