(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear j)
		(clear l)
		(clear m)
		(clear o)
		(handempty)
		(on a h)
		(on b a)
		(on c b)
		(on e d)
		(on g k)
		(on h n)
		(on i c)
		(on j i)
		(on l f)
		(on m e)
		(on o g)
		(ontable d)
		(ontable f)
		(ontable k)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
