(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear k)
		(handempty)
		(on a e)
		(on b f)
		(on c n)
		(on d c)
		(on e i)
		(on f l)
		(on g a)
		(on i j)
		(on j b)
		(on k o)
		(on l d)
		(on m g)
		(on n h)
		(on o m)
		(ontable h)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
