(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear h)
		(clear k)
		(clear m)
		(handempty)
		(on a g)
		(on b j)
		(on c e)
		(on d o)
		(on e l)
		(on g n)
		(on j i)
		(on k a)
		(on l d)
		(on n c)
		(on o f)
		(ontable f)
		(ontable h)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
