(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear j)
		(clear m)
		(clear o)
		(handempty)
		(on a k)
		(on c g)
		(on d e)
		(on e h)
		(on g f)
		(on h n)
		(on i a)
		(on k d)
		(on l c)
		(on m l)
		(on o i)
		(ontable b)
		(ontable f)
		(ontable j)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
