(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear h)
		(clear o)
		(handempty)
		(on a c)
		(on c n)
		(on d i)
		(on e g)
		(on f a)
		(on g l)
		(on h j)
		(on j e)
		(on l k)
		(on o m)
		(ontable b)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
