(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear f)
		(clear j)
		(clear l)
		(clear m)
		(clear n)
		(clear o)
		(handempty)
		(on a c)
		(on c d)
		(on d e)
		(on e h)
		(on g a)
		(on j i)
		(on l g)
		(on n k)
		(ontable b)
		(ontable f)
		(ontable h)
		(ontable i)
		(ontable k)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
