(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear d)
		(clear h)
		(clear o)
		(handempty)
		(on c e)
		(on d l)
		(on e g)
		(on g i)
		(on h n)
		(on i j)
		(on j k)
		(on k a)
		(on l m)
		(on m f)
		(on o c)
		(ontable a)
		(ontable b)
		(ontable f)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
