(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(handempty)
		(on a k)
		(on b j)
		(on c l)
		(on d e)
		(on e h)
		(on f g)
		(on g o)
		(on h n)
		(on j i)
		(on k b)
		(on l m)
		(on n c)
		(ontable i)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
