(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear e)
		(clear h)
		(clear l)
		(handempty)
		(on a m)
		(on b f)
		(on c o)
		(on e j)
		(on f c)
		(on g i)
		(on h b)
		(on j n)
		(on k a)
		(on l k)
		(on o g)
		(ontable d)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
