(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear l)
		(handempty)
		(on a m)
		(on b a)
		(on c f)
		(on d h)
		(on e n)
		(on g c)
		(on h g)
		(on i j)
		(on j k)
		(on k b)
		(on l i)
		(on m o)
		(on n d)
		(ontable f)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
