(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear o)
		(handempty)
		(on b h)
		(on c k)
		(on d e)
		(on f n)
		(on g j)
		(on h c)
		(on j l)
		(on k d)
		(on l i)
		(on n b)
		(on o m)
		(ontable a)
		(ontable e)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
