(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear g)
		(clear h)
		(clear k)
		(clear l)
		(handempty)
		(on b e)
		(on d f)
		(on f m)
		(on h j)
		(on j i)
		(on k n)
		(on m o)
		(on n c)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable i)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
