(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear e)
		(clear g)
		(handempty)
		(on a b)
		(on b n)
		(on d k)
		(on g m)
		(on h o)
		(on i h)
		(on j i)
		(on k j)
		(on m f)
		(on n d)
		(on o l)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
