(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear g)
		(handempty)
		(on a c)
		(on b k)
		(on c l)
		(on e i)
		(on f h)
		(on g e)
		(on h j)
		(on i f)
		(on j b)
		(on k n)
		(on l d)
		(on n o)
		(on o m)
		(ontable d)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
