(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear m)
		(clear n)
		(handempty)
		(on a k)
		(on b j)
		(on c g)
		(on d a)
		(on f l)
		(on g h)
		(on h d)
		(on j i)
		(on k b)
		(on m o)
		(on n f)
		(on o c)
		(ontable e)
		(ontable i)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
