(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear j)
		(clear k)
		(clear o)
		(handempty)
		(on b g)
		(on c f)
		(on d h)
		(on e c)
		(on f l)
		(on g n)
		(on h e)
		(on i a)
		(on j b)
		(on l m)
		(on n d)
		(on o i)
		(ontable a)
		(ontable k)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
