(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear d)
		(clear f)
		(clear l)
		(clear m)
		(handempty)
		(on a o)
		(on d i)
		(on g e)
		(on h g)
		(on l n)
		(on m j)
		(on n k)
		(on o h)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable i)
		(ontable j)
		(ontable k)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
