(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear g)
		(clear k)
		(clear l)
		(handempty)
		(on d i)
		(on e h)
		(on f j)
		(on h f)
		(on i c)
		(on j a)
		(on l e)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable g)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
