(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear g)
		(clear h)
		(clear l)
		(handempty)
		(on b k)
		(on d i)
		(on f a)
		(on h j)
		(on i c)
		(on l e)
		(ontable a)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
