(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear h)
		(clear k)
		(clear l)
		(handempty)
		(on a b)
		(on b e)
		(on c g)
		(on e i)
		(on g j)
		(on h f)
		(on i d)
		(on k a)
		(ontable d)
		(ontable f)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
