(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear g)
		(clear h)
		(holding a)
		(on b d)
		(on d i)
		(on e j)
		(on f k)
		(on g e)
		(on h l)
		(on i c)
		(on j f)
		(ontable c)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
