(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear k)
		(holding h)
		(on b d)
		(on d i)
		(on e j)
		(on g e)
		(on i c)
		(on j l)
		(on k g)
		(on l f)
		(ontable a)
		(ontable c)
		(ontable f)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
