(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(handempty)
		(on a k)
		(on d i)
		(on e b)
		(on f h)
		(on g a)
		(on h g)
		(on i c)
		(on k l)
		(on l j)
		(ontable b)
		(ontable c)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
