(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear d)
		(clear f)
		(clear g)
		(clear h)
		(clear j)
		(clear l)
		(handempty)
		(on a k)
		(on g b)
		(on h i)
		(on j a)
		(on l e)
		(ontable b)
		(ontable c)
		(ontable d)
		(ontable e)
		(ontable f)
		(ontable i)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
