(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear h)
		(handempty)
		(on a c)
		(on b f)
		(on c j)
		(on e l)
		(on f e)
		(on h k)
		(on i d)
		(on j i)
		(on k g)
		(ontable d)
		(ontable g)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
