(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear i)
		(handempty)
		(on b f)
		(on d e)
		(on e g)
		(on f j)
		(on i c)
		(on j l)
		(on k h)
		(on l k)
		(ontable a)
		(ontable c)
		(ontable g)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
