(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(clear i)
		(clear l)
		(holding h)
		(on a c)
		(on b k)
		(on d b)
		(on e g)
		(on j a)
		(on l j)
		(ontable c)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
