(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(clear k)
		(holding b)
		(on a e)
		(on d i)
		(on g j)
		(on i c)
		(on j l)
		(on k g)
		(on l h)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
