(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear e)
		(clear i)
		(clear k)
		(holding d)
		(on a b)
		(on b g)
		(on e h)
		(on f l)
		(on h j)
		(on i c)
		(on j f)
		(ontable c)
		(ontable g)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
