(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear h)
		(clear i)
		(clear k)
		(holding j)
		(on d g)
		(on g b)
		(on h l)
		(on i c)
		(on k e)
		(on l f)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable f)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
