(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear i)
		(clear k)
		(holding e)
		(on a g)
		(on b l)
		(on c h)
		(on d f)
		(on f b)
		(on k d)
		(on l j)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
