(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear h)
		(clear j)
		(holding k)
		(on a g)
		(on b d)
		(on d i)
		(on e b)
		(on f e)
		(on h l)
		(on i c)
		(on j f)
		(ontable c)
		(ontable g)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
