(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear f)
		(clear l)
		(holding i)
		(on a e)
		(on b d)
		(on c k)
		(on e j)
		(on g b)
		(on k h)
		(on l g)
		(ontable d)
		(ontable f)
		(ontable h)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
