(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear h)
		(clear j)
		(handempty)
		(on a c)
		(on b e)
		(on c i)
		(on d a)
		(on e g)
		(on g l)
		(on i k)
		(on k b)
		(on l f)
		(ontable f)
		(ontable h)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
