(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(clear j)
		(holding k)
		(on a l)
		(on b d)
		(on d a)
		(on e i)
		(on g f)
		(on i c)
		(on j g)
		(on l h)
		(ontable c)
		(ontable f)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
