(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear d)
		(clear i)
		(clear k)
		(clear n)
		(holding e)
		(on b o)
		(on d b)
		(on f j)
		(on g m)
		(on h p)
		(on i f)
		(on j l)
		(on k a)
		(on l g)
		(on m h)
		(ontable a)
		(ontable c)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
