(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear d)
		(clear i)
		(clear n)
		(clear p)
		(holding b)
		(on c k)
		(on d c)
		(on f e)
		(on h m)
		(on i g)
		(on k a)
		(on l f)
		(on m l)
		(on n j)
		(on o h)
		(on p o)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable j)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
