(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear i)
		(clear l)
		(clear o)
		(handempty)
		(on c k)
		(on f n)
		(on g c)
		(on h p)
		(on i d)
		(on k a)
		(on m g)
		(on n m)
		(on o h)
		(on p j)
		(ontable a)
		(ontable b)
		(ontable d)
		(ontable e)
		(ontable j)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
