(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear f)
		(handempty)
		(on b o)
		(on c k)
		(on d j)
		(on e d)
		(on f p)
		(on i n)
		(on k a)
		(on l m)
		(on m h)
		(on n g)
		(on o i)
		(on p l)
		(ontable a)
		(ontable g)
		(ontable h)
		(ontable j)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
