(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear e)
		(clear h)
		(clear i)
		(clear o)
		(handempty)
		(on b d)
		(on c k)
		(on d c)
		(on e j)
		(on g f)
		(on h n)
		(on j p)
		(on k a)
		(on m l)
		(on n b)
		(on o g)
		(on p m)
		(ontable a)
		(ontable f)
		(ontable i)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
