(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear j)
		(clear o)
		(clear p)
		(holding i)
		(on b d)
		(on c k)
		(on d c)
		(on f n)
		(on g m)
		(on h l)
		(on j h)
		(on k a)
		(on l e)
		(on o f)
		(on p g)
		(ontable a)
		(ontable e)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
