(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear b)
		(clear e)
		(clear i)
		(clear m)
		(clear n)
		(handempty)
		(on a k)
		(on c o)
		(on e h)
		(on f g)
		(on h p)
		(on i d)
		(on j l)
		(on m f)
		(on n c)
		(on p j)
		(ontable b)
		(ontable d)
		(ontable g)
		(ontable k)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
