(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear e)
		(clear m)
		(clear n)
		(holding d)
		(on a l)
		(on b j)
		(on c b)
		(on e c)
		(on f g)
		(on g h)
		(on k p)
		(on l k)
		(on m o)
		(on n i)
		(on o f)
		(ontable h)
		(ontable i)
		(ontable j)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
