(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear f)
		(clear m)
		(clear n)
		(handempty)
		(on b p)
		(on c k)
		(on d c)
		(on e i)
		(on f h)
		(on h o)
		(on i d)
		(on j b)
		(on k a)
		(on l e)
		(on m l)
		(on n j)
		(on o g)
		(ontable a)
		(ontable g)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
