(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear i)
		(clear l)
		(holding g)
		(on b j)
		(on c k)
		(on d b)
		(on e h)
		(on f n)
		(on h o)
		(on i f)
		(on j p)
		(on k a)
		(on l e)
		(on m d)
		(on n c)
		(on o m)
		(ontable a)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
