(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear h)
		(clear l)
		(clear n)
		(holding g)
		(on b d)
		(on c k)
		(on d c)
		(on e f)
		(on f m)
		(on h o)
		(on i b)
		(on k a)
		(on l p)
		(on m i)
		(on o e)
		(on p j)
		(ontable a)
		(ontable j)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
