(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear f)
		(clear k)
		(handempty)
		(on b p)
		(on c m)
		(on d e)
		(on e j)
		(on g h)
		(on h l)
		(on i o)
		(on j i)
		(on k d)
		(on l n)
		(on m g)
		(ontable a)
		(ontable f)
		(ontable n)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
