(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear g)
		(clear h)
		(holding o)
		(on b p)
		(on c k)
		(on d c)
		(on e l)
		(on f j)
		(on g b)
		(on h m)
		(on i n)
		(on j e)
		(on k a)
		(on l i)
		(on n d)
		(on p f)
		(ontable a)
		(ontable m)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
