(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear b)
		(clear i)
		(clear j)
		(clear m)
		(clear n)
		(handempty)
		(on b d)
		(on c k)
		(on d c)
		(on f p)
		(on g h)
		(on h o)
		(on j l)
		(on k a)
		(on l g)
		(on n f)
		(on o e)
		(ontable a)
		(ontable e)
		(ontable i)
		(ontable m)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
