(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear g)
		(clear h)
		(clear i)
		(clear l)
		(handempty)
		(on b j)
		(on c k)
		(on d b)
		(on f e)
		(on g m)
		(on h n)
		(on j p)
		(on k a)
		(on l o)
		(on m f)
		(on n d)
		(on p c)
		(ontable a)
		(ontable e)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
