(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear g)
		(clear j)
		(clear m)
		(clear p)
		(holding b)
		(on c k)
		(on d c)
		(on e i)
		(on f h)
		(on i f)
		(on j n)
		(on k a)
		(on l d)
		(on m l)
		(on o e)
		(on p o)
		(ontable a)
		(ontable g)
		(ontable h)
		(ontable n)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
