(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear a)
		(clear i)
		(clear k)
		(clear l)
		(handempty)
		(on a c)
		(on c b)
		(on d f)
		(on e g)
		(on f j)
		(on h p)
		(on i h)
		(on j o)
		(on l d)
		(on m e)
		(on n m)
		(on o n)
		(ontable b)
		(ontable g)
		(ontable k)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
