(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear f)
		(clear h)
		(clear m)
		(clear p)
		(handempty)
		(on b e)
		(on c i)
		(on d n)
		(on f j)
		(on g o)
		(on h d)
		(on i b)
		(on j g)
		(on k a)
		(on m k)
		(on n l)
		(ontable a)
		(ontable e)
		(ontable l)
		(ontable o)
		(ontable p)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
