(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear c)
		(clear h)
		(handempty)
		(on b p)
		(on c f)
		(on d k)
		(on e o)
		(on f d)
		(on h e)
		(on i b)
		(on j l)
		(on k a)
		(on l g)
		(on m j)
		(on n i)
		(on o n)
		(on p m)
		(ontable a)
		(ontable g)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
