(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear h)
		(clear i)
		(clear o)
		(holding l)
		(on b d)
		(on c k)
		(on d c)
		(on f b)
		(on h j)
		(on i m)
		(on j e)
		(on k a)
		(on m g)
		(on n p)
		(on o n)
		(on p f)
		(ontable a)
		(ontable e)
		(ontable g)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
