(define (problem blocks-16-1)
(:domain blocks)
(:objects k c d b i n p j m l g e a o h f )
		(:init
		(clear f)
		(clear m)
		(clear o)
		(handempty)
		(on b p)
		(on c k)
		(on d c)
		(on e n)
		(on f b)
		(on g j)
		(on i h)
		(on j d)
		(on k a)
		(on m l)
		(on n g)
		(on o e)
		(on p i)
		(ontable a)
		(ontable h)
		(ontable l)
		)
(:goal (and (on d b) (on b p) (on p f) (on f g) (on g k) (on k i) (on i l)
            (on l j) (on j h) (on h a) (on a n) (on n e) (on e m) (on m c)
            (on c o)))
)
