(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear f)
		(clear g)
		(clear l)
		(clear m)
		(clear n)
		(handempty)
		(on a b)
		(on b h)
		(on e a)
		(on g j)
		(on h k)
		(on j e)
		(on k c)
		(on l o)
		(on m i)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
