(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear f)
		(clear m)
		(handempty)
		(on b j)
		(on d h)
		(on e b)
		(on f l)
		(on g n)
		(on h a)
		(on j i)
		(on k d)
		(on l e)
		(on m o)
		(on n k)
		(on o g)
		(ontable a)
		(ontable c)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
