(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear e)
		(clear h)
		(clear k)
		(handempty)
		(on b j)
		(on c n)
		(on e c)
		(on f l)
		(on h o)
		(on j i)
		(on k b)
		(on l m)
		(on m g)
		(on n f)
		(on o d)
		(ontable a)
		(ontable d)
		(ontable g)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
