(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear g)
		(clear m)
		(clear o)
		(handempty)
		(on a d)
		(on b j)
		(on c h)
		(on d k)
		(on e l)
		(on g a)
		(on h f)
		(on j i)
		(on m e)
		(on n c)
		(on o n)
		(ontable f)
		(ontable i)
		(ontable k)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
