(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear l)
		(handempty)
		(on a h)
		(on b e)
		(on c a)
		(on d k)
		(on e g)
		(on g i)
		(on h j)
		(on j f)
		(on l c)
		(ontable f)
		(ontable i)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
