(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(clear g)
		(clear k)
		(handempty)
		(on a l)
		(on d i)
		(on e a)
		(on f b)
		(on i c)
		(on j h)
		(on l j)
		(ontable b)
		(ontable c)
		(ontable g)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
