(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(clear g)
		(clear j)
		(handempty)
		(on a h)
		(on b d)
		(on d f)
		(on f k)
		(on g l)
		(on i a)
		(on j c)
		(on k i)
		(ontable c)
		(ontable e)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
