(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on b i)
		(on d f)
		(on e b)
		(on g a)
		(on i c)
		(on j h)
		(on k d)
		(on l g)
		(ontable a)
		(ontable c)
		(ontable f)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
