(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear g)
		(handempty)
		(on a h)
		(on d k)
		(on e a)
		(on h j)
		(on i c)
		(on j l)
		(on k i)
		(on l f)
		(ontable b)
		(ontable c)
		(ontable f)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
