(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear f)
		(clear i)
		(holding l)
		(on b a)
		(on c h)
		(on e d)
		(on f g)
		(on h k)
		(on j e)
		(on k j)
		(ontable a)
		(ontable d)
		(ontable g)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
