(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(holding i)
		(on a j)
		(on b f)
		(on d e)
		(on e g)
		(on g k)
		(on h l)
		(on j h)
		(on k b)
		(ontable c)
		(ontable f)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
