(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear e)
		(clear j)
		(clear k)
		(handempty)
		(on a l)
		(on d i)
		(on f h)
		(on g d)
		(on h g)
		(on i c)
		(on j f)
		(on l b)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
