(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear e)
		(holding b)
		(on a i)
		(on e l)
		(on f g)
		(on g k)
		(on h j)
		(on i c)
		(on k h)
		(on l f)
		(ontable c)
		(ontable d)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
