(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear i)
		(holding a)
		(on b h)
		(on d b)
		(on e d)
		(on f l)
		(on j g)
		(on k j)
		(on l k)
		(ontable c)
		(ontable g)
		(ontable h)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
