(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(handempty)
		(on a k)
		(on b d)
		(on d i)
		(on e f)
		(on f j)
		(on g h)
		(on i c)
		(on j a)
		(on k l)
		(on l g)
		(ontable c)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
