(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear e)
		(clear f)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on a c)
		(on e i)
		(on h d)
		(on i b)
		(on j h)
		(on l g)
		(ontable b)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable g)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
