(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear i)
		(holding c)
		(on a d)
		(on b e)
		(on f b)
		(on g a)
		(on h g)
		(on i j)
		(on j l)
		(on k h)
		(on l k)
		(ontable d)
		(ontable e)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
