(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear i)
		(holding f)
		(on a j)
		(on b a)
		(on d g)
		(on g h)
		(on h k)
		(on i c)
		(on k l)
		(ontable c)
		(ontable e)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
