(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear g)
		(holding c)
		(on b k)
		(on d b)
		(on e l)
		(on f j)
		(on g i)
		(on h e)
		(on j h)
		(on k a)
		(on l d)
		(ontable a)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
