(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(holding f)
		(on a h)
		(on b e)
		(on c b)
		(on d k)
		(on g i)
		(on h l)
		(on i j)
		(on j d)
		(ontable e)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
