(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear f)
		(clear i)
		(handempty)
		(on a g)
		(on b e)
		(on c d)
		(on d k)
		(on e c)
		(on g h)
		(on h l)
		(on j a)
		(on k j)
		(ontable f)
		(ontable i)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
