(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear i)
		(clear j)
		(clear k)
		(handempty)
		(on a l)
		(on e h)
		(on f g)
		(on h f)
		(on i c)
		(on j a)
		(on k b)
		(on l e)
		(ontable b)
		(ontable c)
		(ontable d)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
