(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(holding c)
		(on a h)
		(on b i)
		(on d b)
		(on e f)
		(on g k)
		(on h g)
		(on i a)
		(on k l)
		(on l j)
		(ontable f)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
