(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear g)
		(clear l)
		(holding j)
		(on a e)
		(on b d)
		(on d i)
		(on e b)
		(on g k)
		(on i c)
		(on k f)
		(on l h)
		(ontable c)
		(ontable f)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
