(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear g)
		(clear j)
		(holding l)
		(on a h)
		(on b e)
		(on d i)
		(on e d)
		(on g k)
		(on i c)
		(on j a)
		(on k b)
		(ontable c)
		(ontable f)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
