(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear l)
		(holding k)
		(on b g)
		(on c d)
		(on d j)
		(on e i)
		(on f a)
		(on g h)
		(on i f)
		(ontable a)
		(ontable h)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
