(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear g)
		(clear h)
		(clear i)
		(holding e)
		(on a f)
		(on b d)
		(on c k)
		(on f j)
		(on g b)
		(on j l)
		(on k a)
		(ontable d)
		(ontable h)
		(ontable i)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
