(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear j)
		(clear k)
		(holding e)
		(on a h)
		(on b g)
		(on d i)
		(on g a)
		(on h l)
		(on j d)
		(on k c)
		(on l f)
		(ontable c)
		(ontable f)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
