(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear g)
		(clear h)
		(clear l)
		(handempty)
		(on a j)
		(on b a)
		(on e d)
		(on f i)
		(on g k)
		(on i c)
		(on k b)
		(on l e)
		(ontable c)
		(ontable d)
		(ontable h)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
