(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(holding k)
		(on b l)
		(on c h)
		(on e b)
		(on f j)
		(on g d)
		(on h i)
		(on i f)
		(on j e)
		(ontable a)
		(ontable d)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
