(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear f)
		(holding g)
		(on a b)
		(on b d)
		(on d i)
		(on e k)
		(on f j)
		(on h a)
		(on i c)
		(on j l)
		(on k h)
		(ontable c)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
