(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear g)
		(clear i)
		(clear j)
		(clear k)
		(holding d)
		(on e f)
		(on f a)
		(on h l)
		(on i c)
		(on j h)
		(on k e)
		(ontable a)
		(ontable b)
		(ontable c)
		(ontable g)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
