(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear e)
		(clear g)
		(clear h)
		(clear k)
		(handempty)
		(on a i)
		(on b j)
		(on d l)
		(on g d)
		(on h b)
		(on j a)
		(on l f)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable i)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
