(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear e)
		(clear i)
		(holding d)
		(on a j)
		(on b h)
		(on e k)
		(on h a)
		(on i c)
		(on j f)
		(on k l)
		(on l g)
		(ontable c)
		(ontable f)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
