(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear i)
		(clear k)
		(handempty)
		(on a j)
		(on d c)
		(on e f)
		(on g h)
		(on i l)
		(on j g)
		(on l a)
		(ontable b)
		(ontable c)
		(ontable f)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
