(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear e)
		(clear h)
		(clear k)
		(handempty)
		(on a i)
		(on c b)
		(on d f)
		(on h j)
		(on i l)
		(on k g)
		(on l d)
		(ontable b)
		(ontable e)
		(ontable f)
		(ontable g)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
