(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear h)
		(holding a)
		(on b d)
		(on d i)
		(on e k)
		(on f j)
		(on g e)
		(on h f)
		(on i c)
		(on j l)
		(on k b)
		(on l g)
		(ontable c)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
