(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear f)
		(clear l)
		(holding e)
		(on b d)
		(on c i)
		(on d g)
		(on f k)
		(on g a)
		(on j h)
		(on l j)
		(ontable a)
		(ontable h)
		(ontable i)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
