(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear i)
		(clear j)
		(clear k)
		(holding l)
		(on a f)
		(on b g)
		(on d b)
		(on g h)
		(on h a)
		(on i c)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
