(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear j)
		(clear k)
		(handempty)
		(on a h)
		(on b a)
		(on c f)
		(on d i)
		(on e l)
		(on f d)
		(on g e)
		(on k g)
		(on l b)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
