(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear e)
		(clear k)
		(clear l)
		(holding b)
		(on a f)
		(on d i)
		(on e d)
		(on f h)
		(on g a)
		(on i c)
		(on j g)
		(on l j)
		(ontable c)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
