(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear i)
		(clear k)
		(holding l)
		(on b f)
		(on c d)
		(on d g)
		(on e h)
		(on f j)
		(on g b)
		(on i e)
		(on j a)
		(ontable a)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
