(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear l)
		(handempty)
		(on a k)
		(on b d)
		(on d i)
		(on f h)
		(on i c)
		(on j e)
		(on k b)
		(on l j)
		(ontable c)
		(ontable e)
		(ontable g)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
