(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear g)
		(clear h)
		(handempty)
		(on b d)
		(on d i)
		(on e k)
		(on f j)
		(on g f)
		(on h e)
		(on i c)
		(on j l)
		(on l a)
		(ontable a)
		(ontable c)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
