(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear g)
		(clear i)
		(holding l)
		(on a k)
		(on b d)
		(on d c)
		(on g a)
		(on h e)
		(on i h)
		(on j f)
		(on k j)
		(ontable c)
		(ontable e)
		(ontable f)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
