(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear h)
		(holding k)
		(on b e)
		(on c i)
		(on e g)
		(on h j)
		(on i d)
		(on j l)
		(on l f)
		(ontable a)
		(ontable d)
		(ontable f)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
