(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear d)
		(clear f)
		(clear g)
		(clear k)
		(handempty)
		(on a j)
		(on b i)
		(on c l)
		(on e c)
		(on g e)
		(on k h)
		(on l b)
		(ontable d)
		(ontable f)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
