(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear f)
		(holding d)
		(on a b)
		(on c j)
		(on e k)
		(on f g)
		(on g h)
		(on h i)
		(on i e)
		(on j l)
		(ontable b)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
