(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear d)
		(clear e)
		(clear k)
		(holding a)
		(on b g)
		(on c l)
		(on d b)
		(on e i)
		(on f j)
		(on g h)
		(on k c)
		(on l f)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
