(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear g)
		(clear i)
		(handempty)
		(on a j)
		(on e h)
		(on g k)
		(on h l)
		(on i c)
		(on j e)
		(on k f)
		(ontable b)
		(ontable c)
		(ontable d)
		(ontable f)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
