(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear h)
		(clear i)
		(clear l)
		(handempty)
		(on a j)
		(on c g)
		(on d b)
		(on f a)
		(on h c)
		(on i d)
		(on j k)
		(on k e)
		(on l f)
		(ontable b)
		(ontable e)
		(ontable g)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
