(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(holding i)
		(on a f)
		(on b g)
		(on d a)
		(on e d)
		(on f h)
		(on g k)
		(on h l)
		(on k e)
		(on l j)
		(ontable c)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
