(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear g)
		(clear l)
		(handempty)
		(on b e)
		(on c i)
		(on d j)
		(on e h)
		(on f d)
		(on g c)
		(on h a)
		(on j k)
		(on k b)
		(on l f)
		(ontable a)
		(ontable i)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
