(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear j)
		(handempty)
		(on a d)
		(on b f)
		(on d l)
		(on e k)
		(on f i)
		(on g e)
		(on i a)
		(on j g)
		(on k h)
		(ontable c)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
