(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear c)
		(clear h)
		(holding e)
		(on a k)
		(on b i)
		(on c d)
		(on d b)
		(on g f)
		(on h j)
		(on i l)
		(on l g)
		(ontable f)
		(ontable j)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
