(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear f)
		(holding i)
		(on a k)
		(on d j)
		(on e d)
		(on f a)
		(on g h)
		(on j l)
		(on k g)
		(ontable b)
		(ontable c)
		(ontable h)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
