(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear h)
		(clear i)
		(handempty)
		(on a d)
		(on d e)
		(on g k)
		(on h j)
		(on i g)
		(on j l)
		(on l f)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
