(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear f)
		(holding j)
		(on a i)
		(on b e)
		(on d g)
		(on e k)
		(on f l)
		(on g h)
		(on i c)
		(ontable c)
		(ontable h)
		(ontable k)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
