(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear b)
		(clear f)
		(clear k)
		(holding g)
		(on b a)
		(on d e)
		(on e h)
		(on f i)
		(on h j)
		(on i d)
		(on k l)
		(on l c)
		(ontable a)
		(ontable c)
		(ontable j)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
