(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear f)
		(clear i)
		(handempty)
		(on a k)
		(on b e)
		(on c d)
		(on d b)
		(on e h)
		(on f j)
		(on g a)
		(on i g)
		(on k l)
		(ontable h)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
