(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear f)
		(clear h)
		(holding e)
		(on a d)
		(on b j)
		(on d i)
		(on f b)
		(on g l)
		(on h k)
		(on i c)
		(on k g)
		(ontable c)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
