(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear f)
		(clear i)
		(clear j)
		(clear l)
		(handempty)
		(on a b)
		(on b e)
		(on d a)
		(on e g)
		(on i d)
		(on j c)
		(on k h)
		(on l k)
		(ontable c)
		(ontable f)
		(ontable g)
		(ontable h)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
