(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear a)
		(clear j)
		(clear k)
		(handempty)
		(on a e)
		(on c h)
		(on d g)
		(on e d)
		(on f i)
		(on g l)
		(on i b)
		(on j c)
		(on l f)
		(ontable b)
		(ontable h)
		(ontable k)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
