(define (problem blocks-12-0)
(:domain blocks)
(:objects i d b e k g a f c j l h )
		(:init
		(clear c)
		(clear i)
		(holding d)
		(on a g)
		(on b k)
		(on c b)
		(on e l)
		(on f a)
		(on g h)
		(on h j)
		(on i e)
		(on k f)
		(ontable j)
		(ontable l)
		)
(:goal (and (on i c) (on c b) (on b l) (on l d) (on d j) (on j e) (on e k)
            (on k f) (on f a) (on a h) (on h g)))
)
