(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear c)
		(clear d)
		(clear n)
		(holding i)
		(on a l)
		(on b h)
		(on d j)
		(on e b)
		(on f a)
		(on h k)
		(on j f)
		(on k m)
		(on l g)
		(on n e)
		(ontable c)
		(ontable g)
		(ontable m)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
