(define (problem blocks-14-0)
(:domain blocks)
(:objects i d b l c k m h j n e f g a )
		(:init
		(clear b)
		(clear e)
		(clear h)
		(holding l)
		(on a f)
		(on b c)
		(on c k)
		(on d i)
		(on f g)
		(on g d)
		(on i n)
		(on j a)
		(on k m)
		(on m j)
		(ontable e)
		(ontable h)
		(ontable n)
		)
(:goal (and (on e l) (on l f) (on f b) (on b j) (on j i) (on i n) (on n c)
            (on c k) (on k g) (on g d) (on d m) (on m a) (on a h)))
)
