(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear i)
		(clear j)
		(handempty)
		(on a n)
		(on b a)
		(on c l)
		(on d b)
		(on e c)
		(on h k)
		(on i o)
		(on j h)
		(on k f)
		(on l m)
		(on m g)
		(on o e)
		(ontable f)
		(ontable g)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
