(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear i)
		(clear j)
		(clear k)
		(clear n)
		(handempty)
		(on a e)
		(on b a)
		(on c f)
		(on d l)
		(on e h)
		(on g d)
		(on h c)
		(on j g)
		(on k b)
		(on l o)
		(on o m)
		(ontable f)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
