(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear h)
		(clear m)
		(handempty)
		(on a k)
		(on b j)
		(on c f)
		(on d g)
		(on e n)
		(on g l)
		(on h a)
		(on j i)
		(on k b)
		(on l e)
		(on n o)
		(on o c)
		(ontable f)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
