(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear j)
		(clear k)
		(handempty)
		(on a n)
		(on b o)
		(on c h)
		(on d m)
		(on f l)
		(on i d)
		(on k c)
		(on l g)
		(on m f)
		(on n e)
		(on o i)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable j)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
