(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear d)
		(clear g)
		(handempty)
		(on a k)
		(on b j)
		(on c o)
		(on d a)
		(on e n)
		(on f l)
		(on g m)
		(on j i)
		(on k b)
		(on m h)
		(on n f)
		(on o e)
		(ontable h)
		(ontable i)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
