(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear i)
		(clear k)
		(clear m)
		(clear o)
		(handempty)
		(on a b)
		(on b c)
		(on c e)
		(on e g)
		(on f l)
		(on h f)
		(on i n)
		(on j a)
		(on m h)
		(on n j)
		(on o d)
		(ontable d)
		(ontable g)
		(ontable k)
		(ontable l)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
