(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear c)
		(clear g)
		(clear k)
		(clear m)
		(clear n)
		(clear o)
		(handempty)
		(on a f)
		(on b j)
		(on c h)
		(on f e)
		(on g l)
		(on j i)
		(on m a)
		(on o d)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable k)
		(ontable l)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
