(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear f)
		(clear k)
		(clear o)
		(handempty)
		(on a g)
		(on b j)
		(on c h)
		(on d c)
		(on e m)
		(on g d)
		(on h l)
		(on j i)
		(on k b)
		(on l e)
		(on m n)
		(on o a)
		(ontable f)
		(ontable i)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
