(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear i)
		(clear j)
		(clear k)
		(handempty)
		(on a d)
		(on b h)
		(on c f)
		(on d g)
		(on e l)
		(on f m)
		(on h e)
		(on k o)
		(on l n)
		(on n c)
		(on o a)
		(ontable g)
		(ontable i)
		(ontable j)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
