(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear k)
		(handempty)
		(on a d)
		(on b j)
		(on d n)
		(on e c)
		(on f g)
		(on g o)
		(on h f)
		(on j i)
		(on k e)
		(on l h)
		(on n l)
		(on o m)
		(ontable c)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
