(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear e)
		(clear i)
		(clear n)
		(handempty)
		(on a h)
		(on b k)
		(on c b)
		(on f l)
		(on g m)
		(on h f)
		(on j c)
		(on k a)
		(on l o)
		(on n j)
		(on o g)
		(ontable d)
		(ontable e)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
