(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear j)
		(handempty)
		(on c h)
		(on d e)
		(on e n)
		(on f g)
		(on g o)
		(on i l)
		(on j i)
		(on k d)
		(on l k)
		(on n f)
		(on o m)
		(ontable a)
		(ontable b)
		(ontable h)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
