(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear i)
		(clear k)
		(clear l)
		(clear n)
		(clear o)
		(handempty)
		(on a d)
		(on d h)
		(on g m)
		(on i e)
		(on l g)
		(on m f)
		(on n c)
		(on o j)
		(ontable b)
		(ontable c)
		(ontable e)
		(ontable f)
		(ontable h)
		(ontable j)
		(ontable k)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
