(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear d)
		(clear k)
		(clear n)
		(handempty)
		(on b j)
		(on c f)
		(on d i)
		(on f g)
		(on g o)
		(on h a)
		(on j e)
		(on k h)
		(on l c)
		(on m l)
		(on n m)
		(ontable a)
		(ontable e)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
