(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear i)
		(clear k)
		(handempty)
		(on a h)
		(on b j)
		(on c a)
		(on d e)
		(on e n)
		(on f d)
		(on g m)
		(on h f)
		(on j c)
		(on k b)
		(on l g)
		(on n o)
		(on o l)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
