(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear i)
		(clear j)
		(clear k)
		(handempty)
		(on a g)
		(on b d)
		(on d n)
		(on e c)
		(on f l)
		(on g b)
		(on i m)
		(on j h)
		(on k o)
		(on l e)
		(on o f)
		(ontable c)
		(ontable h)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
