(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear d)
		(clear h)
		(clear i)
		(clear o)
		(handempty)
		(on a m)
		(on b l)
		(on c n)
		(on e a)
		(on f g)
		(on h j)
		(on i e)
		(on j f)
		(on k b)
		(on n k)
		(ontable d)
		(ontable g)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
