(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear f)
		(clear g)
		(clear j)
		(handempty)
		(on a b)
		(on b c)
		(on c h)
		(on d a)
		(on e k)
		(on g o)
		(on i d)
		(on j n)
		(on k l)
		(on l m)
		(on m i)
		(on n e)
		(ontable f)
		(ontable h)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
