(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear h)
		(handempty)
		(on a l)
		(on b j)
		(on d e)
		(on e c)
		(on f m)
		(on g n)
		(on h k)
		(on j i)
		(on k a)
		(on l o)
		(on m g)
		(on n d)
		(on o f)
		(ontable c)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
