(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear c)
		(clear i)
		(clear j)
		(clear k)
		(handempty)
		(on b h)
		(on c n)
		(on f m)
		(on g o)
		(on h l)
		(on k e)
		(on l f)
		(on m g)
		(on n d)
		(ontable a)
		(ontable d)
		(ontable e)
		(ontable i)
		(ontable j)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
