(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear b)
		(clear h)
		(clear k)
		(handempty)
		(on a d)
		(on b j)
		(on d g)
		(on f e)
		(on g m)
		(on h l)
		(on j i)
		(on k o)
		(on l f)
		(on m n)
		(on n c)
		(ontable c)
		(ontable e)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
