(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear i)
		(clear k)
		(handempty)
		(on a g)
		(on b a)
		(on c n)
		(on d m)
		(on e c)
		(on g h)
		(on i e)
		(on k j)
		(on m l)
		(on n o)
		(ontable f)
		(ontable h)
		(ontable j)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
