(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear h)
		(clear i)
		(clear j)
		(handempty)
		(on a n)
		(on b d)
		(on d c)
		(on e m)
		(on f o)
		(on h k)
		(on j b)
		(on l g)
		(on m f)
		(on n e)
		(on o l)
		(ontable c)
		(ontable g)
		(ontable i)
		(ontable k)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
