(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear f)
		(clear g)
		(clear h)
		(handempty)
		(on a l)
		(on b j)
		(on c o)
		(on d e)
		(on e c)
		(on f m)
		(on h a)
		(on j i)
		(on k b)
		(on l k)
		(on o n)
		(ontable g)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
