(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear e)
		(clear l)
		(handempty)
		(on a o)
		(on b j)
		(on e n)
		(on f b)
		(on g h)
		(on h m)
		(on j i)
		(on k f)
		(on l k)
		(on n d)
		(on o g)
		(ontable c)
		(ontable d)
		(ontable i)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
