(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear g)
		(clear i)
		(handempty)
		(on a e)
		(on b o)
		(on c l)
		(on f a)
		(on g n)
		(on i j)
		(on k h)
		(on l k)
		(on m c)
		(on o m)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable j)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
