(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear e)
		(clear l)
		(clear m)
		(handempty)
		(on a k)
		(on b j)
		(on c d)
		(on d a)
		(on e o)
		(on g h)
		(on j i)
		(on k b)
		(on l n)
		(on m f)
		(on n g)
		(on o c)
		(ontable f)
		(ontable h)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
