(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear c)
		(clear g)
		(clear k)
		(handempty)
		(on a d)
		(on b j)
		(on c f)
		(on d b)
		(on f m)
		(on g n)
		(on h l)
		(on j i)
		(on k h)
		(on l e)
		(on m o)
		(ontable e)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
