(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear h)
		(clear l)
		(clear m)
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on c g)
		(on d a)
		(on f e)
		(on g f)
		(on j i)
		(on k b)
		(on l d)
		(on o n)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
