(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear j)
		(handempty)
		(on a m)
		(on b h)
		(on c n)
		(on d o)
		(on e k)
		(on g d)
		(on h a)
		(on j g)
		(on k i)
		(on l c)
		(on m l)
		(ontable f)
		(ontable i)
		(ontable n)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
