(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear e)
		(clear f)
		(clear h)
		(clear m)
		(clear n)
		(handempty)
		(on a i)
		(on b j)
		(on c l)
		(on d g)
		(on e o)
		(on g k)
		(on h b)
		(on n c)
		(ontable f)
		(ontable i)
		(ontable j)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
