(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear d)
		(clear h)
		(clear m)
		(clear o)
		(handempty)
		(on b j)
		(on c e)
		(on d k)
		(on e b)
		(on f l)
		(on h g)
		(on j i)
		(on k a)
		(on l n)
		(on o f)
		(ontable a)
		(ontable g)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
