(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear h)
		(clear i)
		(clear j)
		(clear k)
		(clear n)
		(handempty)
		(on a l)
		(on d c)
		(on e b)
		(on f o)
		(on h g)
		(on i a)
		(on l m)
		(on m f)
		(on n e)
		(ontable b)
		(ontable c)
		(ontable g)
		(ontable j)
		(ontable k)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
