(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear h)
		(clear k)
		(clear n)
		(handempty)
		(on a l)
		(on c m)
		(on d b)
		(on e g)
		(on f i)
		(on g a)
		(on h e)
		(on j f)
		(on k j)
		(on m o)
		(on n c)
		(ontable b)
		(ontable i)
		(ontable l)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
