(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear b)
		(clear c)
		(clear i)
		(clear j)
		(handempty)
		(on a k)
		(on b a)
		(on d e)
		(on e g)
		(on f d)
		(on g o)
		(on h m)
		(on k l)
		(on l f)
		(on n h)
		(on o n)
		(ontable c)
		(ontable i)
		(ontable j)
		(ontable m)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
