(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear c)
		(clear i)
		(clear j)
		(clear n)
		(handempty)
		(on a k)
		(on b a)
		(on c b)
		(on d m)
		(on g o)
		(on h g)
		(on j f)
		(on l e)
		(on m l)
		(on n h)
		(on o d)
		(ontable e)
		(ontable f)
		(ontable i)
		(ontable k)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
