(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear d)
		(clear f)
		(clear g)
		(clear m)
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on c n)
		(on f a)
		(on g e)
		(on j i)
		(on k b)
		(on l h)
		(on m c)
		(on n l)
		(ontable d)
		(ontable e)
		(ontable h)
		(ontable i)
		(ontable o)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
