(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on c l)
		(on d a)
		(on e m)
		(on f h)
		(on g e)
		(on h d)
		(on j i)
		(on k b)
		(on l f)
		(on m n)
		(on n c)
		(on o g)
		(ontable i)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
