(define (problem blocks-15-1)
(:domain blocks)
(:objects j b k a d h e n c f l m i o g )
		(:init
		(clear a)
		(clear d)
		(clear e)
		(clear h)
		(clear o)
		(handempty)
		(on a k)
		(on b j)
		(on d f)
		(on e m)
		(on h l)
		(on j i)
		(on k b)
		(on l n)
		(on m g)
		(on o c)
		(ontable c)
		(ontable f)
		(ontable g)
		(ontable i)
		(ontable n)
		)
(:goal (and (on d g) (on g f) (on f k) (on k j) (on j e) (on e m) (on m a)
            (on a b) (on b c) (on c n) (on n o) (on o i) (on i l) (on l h)))
)
