(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear h)
		(clear i)
		(clear l)
		(handempty)
		(on b j)
		(on c g)
		(on d a)
		(on e m)
		(on i d)
		(on l c)
		(on m o)
		(on n k)
		(on o n)
		(ontable a)
		(ontable f)
		(ontable g)
		(ontable h)
		(ontable j)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
