(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear f)
		(clear i)
		(clear l)
		(handempty)
		(on a h)
		(on c g)
		(on d n)
		(on e m)
		(on f j)
		(on j k)
		(on k o)
		(on l c)
		(on o a)
		(ontable b)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
