(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear i)
		(clear l)
		(clear m)
		(clear n)
		(handempty)
		(on b o)
		(on c b)
		(on d j)
		(on e k)
		(on f c)
		(on g e)
		(on k d)
		(on l h)
		(on m f)
		(on n g)
		(on o a)
		(ontable a)
		(ontable h)
		(ontable i)
		(ontable j)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
