(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear e)
		(clear f)
		(clear h)
		(clear k)
		(handempty)
		(on b j)
		(on c g)
		(on d l)
		(on f n)
		(on h m)
		(on i b)
		(on j o)
		(on l c)
		(on n i)
		(on o a)
		(ontable a)
		(ontable e)
		(ontable g)
		(ontable k)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
