(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear d)
		(clear i)
		(clear m)
		(handempty)
		(on a h)
		(on b k)
		(on c g)
		(on d e)
		(on e j)
		(on g b)
		(on i o)
		(on j n)
		(on k f)
		(on m l)
		(on n c)
		(ontable f)
		(ontable h)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
