(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear e)
		(clear m)
		(handempty)
		(on a b)
		(on b j)
		(on c l)
		(on d n)
		(on e f)
		(on f o)
		(on g c)
		(on h a)
		(on i h)
		(on j k)
		(on m g)
		(on n i)
		(ontable k)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
