(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear n)
		(clear o)
		(handempty)
		(on a l)
		(on b i)
		(on d j)
		(on e f)
		(on f m)
		(on g a)
		(on i h)
		(on j b)
		(on l k)
		(on m g)
		(on n e)
		(ontable c)
		(ontable h)
		(ontable k)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
