(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear f)
		(clear h)
		(clear j)
		(clear n)
		(handempty)
		(on b e)
		(on c g)
		(on f m)
		(on h k)
		(on i d)
		(on j o)
		(on l c)
		(on m l)
		(on n a)
		(on o i)
		(ontable a)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
