(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear c)
		(clear d)
		(handempty)
		(on a b)
		(on b i)
		(on c e)
		(on d o)
		(on e m)
		(on f h)
		(on i j)
		(on j l)
		(on k n)
		(on l k)
		(on m f)
		(on n g)
		(ontable g)
		(ontable h)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
