(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear o)
		(handempty)
		(on a h)
		(on b f)
		(on c g)
		(on d a)
		(on e m)
		(on f i)
		(on h n)
		(on i j)
		(on j l)
		(on l c)
		(on m k)
		(on n b)
		(on o d)
		(ontable g)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
