(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear i)
		(clear m)
		(handempty)
		(on a j)
		(on c g)
		(on d l)
		(on e f)
		(on h o)
		(on i b)
		(on j d)
		(on k h)
		(on l c)
		(on m k)
		(on o n)
		(ontable b)
		(ontable f)
		(ontable g)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
