(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear h)
		(clear m)
		(clear o)
		(handempty)
		(on a b)
		(on b i)
		(on c g)
		(on e k)
		(on f l)
		(on i e)
		(on j a)
		(on m n)
		(on n f)
		(on o j)
		(ontable d)
		(ontable g)
		(ontable h)
		(ontable k)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
