(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear d)
		(clear j)
		(clear m)
		(handempty)
		(on a e)
		(on b n)
		(on c f)
		(on d b)
		(on e h)
		(on f k)
		(on g i)
		(on h l)
		(on i c)
		(on j o)
		(on l g)
		(ontable k)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
