(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear e)
		(clear f)
		(clear l)
		(handempty)
		(on c k)
		(on d a)
		(on e d)
		(on f g)
		(on g i)
		(on h n)
		(on i j)
		(on j b)
		(on k m)
		(on l o)
		(on o h)
		(ontable a)
		(ontable b)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
