(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear n)
		(handempty)
		(on a d)
		(on c g)
		(on d h)
		(on f a)
		(on h k)
		(on i j)
		(on j c)
		(on k l)
		(on l m)
		(on m i)
		(on n o)
		(ontable b)
		(ontable e)
		(ontable g)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
