(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear g)
		(clear k)
		(clear o)
		(handempty)
		(on a f)
		(on b i)
		(on e b)
		(on f h)
		(on g m)
		(on h n)
		(on i j)
		(on j l)
		(on k e)
		(on l d)
		(on m a)
		(ontable c)
		(ontable d)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
