(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear e)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on a o)
		(on b m)
		(on c g)
		(on d i)
		(on e d)
		(on f h)
		(on j c)
		(on l a)
		(on m n)
		(on n f)
		(ontable g)
		(ontable h)
		(ontable i)
		(ontable k)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
