(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear f)
		(clear h)
		(clear k)
		(handempty)
		(on a i)
		(on b a)
		(on c g)
		(on d l)
		(on f d)
		(on h j)
		(on i o)
		(on j e)
		(on k n)
		(on l c)
		(on n b)
		(on o m)
		(ontable e)
		(ontable g)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
