(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear e)
		(clear g)
		(handempty)
		(on a o)
		(on b a)
		(on c m)
		(on e j)
		(on f h)
		(on g k)
		(on h i)
		(on i b)
		(on j n)
		(on l f)
		(on m l)
		(ontable d)
		(ontable k)
		(ontable n)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
