(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear i)
		(clear l)
		(handempty)
		(on b n)
		(on d g)
		(on e j)
		(on f m)
		(on g a)
		(on h k)
		(on i e)
		(on j f)
		(on l d)
		(on m b)
		(on n o)
		(on o h)
		(ontable a)
		(ontable c)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
