(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear f)
		(clear g)
		(clear h)
		(handempty)
		(on a l)
		(on b i)
		(on c m)
		(on d e)
		(on e j)
		(on f d)
		(on h a)
		(on i o)
		(on j n)
		(on k b)
		(on n k)
		(ontable g)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
