(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear k)
		(clear n)
		(clear o)
		(handempty)
		(on a b)
		(on b m)
		(on c g)
		(on d f)
		(on e i)
		(on h j)
		(on i h)
		(on j l)
		(on k d)
		(on m c)
		(on n a)
		(ontable f)
		(ontable g)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
