(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear f)
		(clear k)
		(clear n)
		(handempty)
		(on a o)
		(on b e)
		(on c g)
		(on d h)
		(on e l)
		(on f a)
		(on g d)
		(on k i)
		(on m j)
		(on n c)
		(on o m)
		(ontable h)
		(ontable i)
		(ontable j)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
