(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear e)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on b a)
		(on c d)
		(on d j)
		(on e g)
		(on f n)
		(on i h)
		(on k b)
		(on l o)
		(on m f)
		(on n i)
		(ontable a)
		(ontable g)
		(ontable h)
		(ontable j)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
