(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear f)
		(clear g)
		(clear j)
		(clear o)
		(handempty)
		(on a k)
		(on b e)
		(on c a)
		(on e h)
		(on f d)
		(on g n)
		(on j l)
		(on l c)
		(on m b)
		(on n m)
		(on o i)
		(ontable d)
		(ontable h)
		(ontable i)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
