(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear k)
		(clear l)
		(clear n)
		(clear o)
		(handempty)
		(on c a)
		(on f c)
		(on h m)
		(on i g)
		(on j d)
		(on k b)
		(on l f)
		(on m i)
		(on n h)
		(on o j)
		(ontable a)
		(ontable b)
		(ontable d)
		(ontable e)
		(ontable g)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
