(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear e)
		(clear i)
		(clear n)
		(handempty)
		(on b f)
		(on d b)
		(on e c)
		(on f h)
		(on g d)
		(on i l)
		(on j m)
		(on k g)
		(on l o)
		(on m k)
		(on o j)
		(ontable a)
		(ontable c)
		(ontable h)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
