(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear i)
		(clear n)
		(handempty)
		(on a l)
		(on b d)
		(on c g)
		(on d o)
		(on e j)
		(on f b)
		(on h f)
		(on i m)
		(on j h)
		(on l c)
		(on m k)
		(on o a)
		(ontable g)
		(ontable k)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
