(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear c)
		(clear d)
		(clear l)
		(clear m)
		(handempty)
		(on a o)
		(on b h)
		(on c e)
		(on d i)
		(on f a)
		(on h f)
		(on i k)
		(on j n)
		(on l g)
		(on o j)
		(ontable e)
		(ontable g)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
