(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear i)
		(clear k)
		(handempty)
		(on a c)
		(on b l)
		(on c f)
		(on e d)
		(on g j)
		(on h g)
		(on i h)
		(on j e)
		(on k m)
		(on l n)
		(on n o)
		(ontable d)
		(ontable f)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
