(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear h)
		(clear i)
		(clear m)
		(clear n)
		(handempty)
		(on b l)
		(on c g)
		(on d e)
		(on e j)
		(on f k)
		(on h o)
		(on i f)
		(on j c)
		(on n d)
		(ontable a)
		(ontable g)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
