(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear b)
		(clear d)
		(clear i)
		(clear j)
		(handempty)
		(on b f)
		(on c k)
		(on d l)
		(on e c)
		(on g m)
		(on i n)
		(on j o)
		(on m h)
		(on n e)
		(on o g)
		(ontable a)
		(ontable f)
		(ontable h)
		(ontable k)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
