(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear f)
		(clear g)
		(clear h)
		(clear j)
		(handempty)
		(on b m)
		(on d i)
		(on e d)
		(on f k)
		(on g l)
		(on h o)
		(on i n)
		(on j c)
		(on l b)
		(on o e)
		(ontable a)
		(ontable c)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
