(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear f)
		(clear h)
		(handempty)
		(on a n)
		(on b k)
		(on c g)
		(on d b)
		(on e a)
		(on f o)
		(on h i)
		(on j l)
		(on k j)
		(on l c)
		(on n d)
		(on o m)
		(ontable g)
		(ontable i)
		(ontable m)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
