(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear f)
		(clear k)
		(clear o)
		(handempty)
		(on a c)
		(on b i)
		(on c d)
		(on d g)
		(on e j)
		(on f n)
		(on h e)
		(on i h)
		(on k m)
		(on m b)
		(on n l)
		(on o a)
		(ontable g)
		(ontable j)
		(ontable l)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
