(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear g)
		(clear h)
		(clear j)
		(clear k)
		(clear l)
		(clear m)
		(handempty)
		(on a o)
		(on b a)
		(on d f)
		(on e n)
		(on f c)
		(on g i)
		(on h e)
		(on j d)
		(on n b)
		(ontable c)
		(ontable i)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
