(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear h)
		(clear i)
		(clear j)
		(clear k)
		(clear l)
		(handempty)
		(on a o)
		(on c g)
		(on d e)
		(on f m)
		(on h b)
		(on i a)
		(on k f)
		(on l c)
		(on o n)
		(ontable b)
		(ontable e)
		(ontable g)
		(ontable j)
		(ontable m)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
