(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear a)
		(clear h)
		(handempty)
		(on a i)
		(on b j)
		(on c g)
		(on d l)
		(on e m)
		(on f o)
		(on h e)
		(on i n)
		(on k d)
		(on l c)
		(on m f)
		(on n k)
		(on o b)
		(ontable g)
		(ontable j)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
