(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear d)
		(clear i)
		(clear l)
		(clear n)
		(handempty)
		(on b h)
		(on c g)
		(on e f)
		(on f m)
		(on h o)
		(on i e)
		(on k a)
		(on l c)
		(on m b)
		(on n j)
		(on o k)
		(ontable a)
		(ontable d)
		(ontable g)
		(ontable j)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
