(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear d)
		(clear e)
		(clear h)
		(handempty)
		(on a o)
		(on b g)
		(on c i)
		(on e c)
		(on h m)
		(on i j)
		(on j l)
		(on k a)
		(on l f)
		(on m n)
		(on n k)
		(ontable d)
		(ontable f)
		(ontable g)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
