(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear d)
		(clear i)
		(clear j)
		(handempty)
		(on a l)
		(on c g)
		(on d h)
		(on e f)
		(on f k)
		(on h o)
		(on i a)
		(on k m)
		(on l c)
		(on m n)
		(on o e)
		(ontable b)
		(ontable g)
		(ontable j)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
