(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear g)
		(clear i)
		(clear o)
		(handempty)
		(on a b)
		(on b f)
		(on d m)
		(on e d)
		(on f n)
		(on h a)
		(on i j)
		(on l h)
		(on m l)
		(on n k)
		(on o e)
		(ontable c)
		(ontable g)
		(ontable j)
		(ontable k)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
