(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear f)
		(clear g)
		(handempty)
		(on a o)
		(on b m)
		(on c l)
		(on d k)
		(on f i)
		(on g c)
		(on i h)
		(on j d)
		(on k b)
		(on l n)
		(on m a)
		(on n j)
		(ontable e)
		(ontable h)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
