(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear e)
		(clear i)
		(clear k)
		(clear m)
		(handempty)
		(on a n)
		(on c g)
		(on d j)
		(on e l)
		(on i d)
		(on j h)
		(on k a)
		(on l c)
		(on m f)
		(on n o)
		(on o b)
		(ontable b)
		(ontable f)
		(ontable g)
		(ontable h)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
