(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear i)
		(clear j)
		(clear m)
		(clear n)
		(handempty)
		(on a o)
		(on b a)
		(on c d)
		(on d f)
		(on f k)
		(on i b)
		(on j e)
		(on k h)
		(on m l)
		(on n g)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable l)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
