(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear b)
		(clear c)
		(clear e)
		(clear h)
		(clear i)
		(clear l)
		(handempty)
		(on b d)
		(on c g)
		(on f n)
		(on i m)
		(on j k)
		(on k o)
		(on l j)
		(on m f)
		(on o a)
		(ontable a)
		(ontable d)
		(ontable e)
		(ontable g)
		(ontable h)
		(ontable n)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
