(define (problem blocks-15-0)
(:domain blocks)
(:objects a c l d j h k o n g i f b m e )
		(:init
		(clear c)
		(clear d)
		(clear f)
		(clear k)
		(handempty)
		(on a o)
		(on b m)
		(on d h)
		(on e l)
		(on f i)
		(on h n)
		(on i e)
		(on j g)
		(on k j)
		(on l b)
		(on n a)
		(ontable c)
		(ontable g)
		(ontable m)
		(ontable o)
		)
(:goal (and (on g o) (on o h) (on h k) (on k m) (on m f) (on f e) (on e a)
            (on a b) (on b l) (on l j) (on j d) (on d n) (on n i) (on i c)))
)
