(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear f)
		(clear o)
		(holding k)
		(on a j)
		(on b m)
		(on c e)
		(on e n)
		(on f q)
		(on g a)
		(on h l)
		(on i b)
		(on j i)
		(on l p)
		(on o h)
		(on p d)
		(on q g)
		(ontable d)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
