(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear g)
		(handempty)
		(on b k)
		(on c o)
		(on d c)
		(on e n)
		(on g m)
		(on h q)
		(on i a)
		(on j l)
		(on k j)
		(on l i)
		(on n p)
		(on p h)
		(on q d)
		(ontable a)
		(ontable f)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
