(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear g)
		(clear k)
		(clear n)
		(clear p)
		(clear q)
		(handempty)
		(on a j)
		(on b m)
		(on d l)
		(on e f)
		(on f h)
		(on g e)
		(on h a)
		(on i b)
		(on j i)
		(on n d)
		(on q o)
		(ontable c)
		(ontable k)
		(ontable l)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
