(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear d)
		(clear f)
		(clear g)
		(clear p)
		(holding j)
		(on a c)
		(on b m)
		(on c i)
		(on e n)
		(on g k)
		(on h a)
		(on i q)
		(on k o)
		(on o l)
		(on p h)
		(on q e)
		(ontable d)
		(ontable f)
		(ontable l)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
