(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear j)
		(clear p)
		(clear q)
		(handempty)
		(on a d)
		(on b m)
		(on d l)
		(on e k)
		(on f g)
		(on g i)
		(on h n)
		(on i b)
		(on j o)
		(on l e)
		(on o a)
		(on p f)
		(on q h)
		(ontable c)
		(ontable k)
		(ontable m)
		(ontable n)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
