(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear h)
		(clear j)
		(clear m)
		(holding d)
		(on a o)
		(on b k)
		(on c a)
		(on e b)
		(on f n)
		(on g l)
		(on i f)
		(on j c)
		(on k i)
		(on n p)
		(on o q)
		(on q g)
		(ontable h)
		(ontable l)
		(ontable m)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
