(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear o)
		(clear p)
		(clear q)
		(handempty)
		(on a j)
		(on b m)
		(on d g)
		(on e k)
		(on f e)
		(on g h)
		(on i b)
		(on j i)
		(on l f)
		(on n c)
		(on o n)
		(on p l)
		(on q d)
		(ontable c)
		(ontable h)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
