(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear g)
		(clear h)
		(clear j)
		(clear q)
		(handempty)
		(on a c)
		(on c b)
		(on d f)
		(on e k)
		(on f p)
		(on g m)
		(on h i)
		(on i n)
		(on j d)
		(on m o)
		(on n e)
		(on q l)
		(ontable b)
		(ontable k)
		(ontable l)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
