(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear i)
		(clear n)
		(clear o)
		(holding c)
		(on a q)
		(on b a)
		(on e k)
		(on f e)
		(on g b)
		(on h m)
		(on j h)
		(on l f)
		(on m g)
		(on n d)
		(on o p)
		(on p j)
		(on q l)
		(ontable d)
		(ontable i)
		(ontable k)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
