(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear c)
		(clear g)
		(clear h)
		(clear l)
		(clear n)
		(clear p)
		(handempty)
		(on b m)
		(on d i)
		(on e k)
		(on f e)
		(on g d)
		(on h a)
		(on i b)
		(on j o)
		(on l j)
		(on n q)
		(on q f)
		(ontable a)
		(ontable c)
		(ontable k)
		(ontable m)
		(ontable o)
		(ontable p)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
