(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear b)
		(clear j)
		(handempty)
		(on b i)
		(on c o)
		(on d c)
		(on e k)
		(on g d)
		(on h n)
		(on i m)
		(on j f)
		(on k p)
		(on l h)
		(on m q)
		(on n e)
		(on p g)
		(on q l)
		(ontable a)
		(ontable f)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
