(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear h)
		(clear l)
		(clear m)
		(handempty)
		(on a p)
		(on b n)
		(on c o)
		(on d c)
		(on e k)
		(on f e)
		(on g d)
		(on h f)
		(on i b)
		(on j a)
		(on k j)
		(on m i)
		(on n g)
		(on p q)
		(ontable l)
		(ontable o)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
