(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear h)
		(clear k)
		(clear n)
		(handempty)
		(on a j)
		(on b m)
		(on c q)
		(on e d)
		(on g c)
		(on h l)
		(on i b)
		(on j i)
		(on l f)
		(on n o)
		(on o p)
		(on p g)
		(on q a)
		(ontable d)
		(ontable f)
		(ontable k)
		(ontable m)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
