(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear g)
		(clear p)
		(clear q)
		(handempty)
		(on a f)
		(on b m)
		(on c o)
		(on d c)
		(on e i)
		(on f j)
		(on h n)
		(on i b)
		(on j k)
		(on k l)
		(on l d)
		(on p a)
		(on q h)
		(ontable g)
		(ontable m)
		(ontable n)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
