(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear a)
		(clear e)
		(clear j)
		(holding q)
		(on a k)
		(on b m)
		(on c o)
		(on d c)
		(on e f)
		(on f i)
		(on g d)
		(on h g)
		(on i b)
		(on j n)
		(on k l)
		(on n p)
		(on p h)
		(ontable l)
		(ontable m)
		(ontable o)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
