(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear b)
		(clear e)
		(clear f)
		(clear i)
		(clear m)
		(handempty)
		(on b o)
		(on d q)
		(on e j)
		(on f d)
		(on g h)
		(on h p)
		(on i k)
		(on j g)
		(on k a)
		(on l n)
		(on m c)
		(on o l)
		(ontable a)
		(ontable c)
		(ontable n)
		(ontable p)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
