(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear m)
		(clear n)
		(holding j)
		(on a h)
		(on b a)
		(on c p)
		(on d c)
		(on e k)
		(on f e)
		(on g l)
		(on i o)
		(on l f)
		(on m b)
		(on n i)
		(on o q)
		(on p g)
		(on q d)
		(ontable h)
		(ontable k)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
