(define (problem blocks-17-0)
(:domain blocks)
(:objects c d e f b i j a n o k m p h g l q )
		(:init
		(clear e)
		(clear g)
		(clear k)
		(handempty)
		(on a j)
		(on b m)
		(on c p)
		(on d c)
		(on e d)
		(on f n)
		(on g f)
		(on h o)
		(on i b)
		(on j i)
		(on l a)
		(on n h)
		(on o l)
		(on p q)
		(ontable k)
		(ontable m)
		(ontable q)
		)
(:goal (and (on q n) (on n l) (on l o) (on o j) (on j h) (on h c) (on c e)
            (on e m) (on m p) (on p a) (on a g) (on g b) (on b i) (on i k)
            (on k f) (on f d)))
)
